import {
    FiFilter, FiCalendar, FiCreditCard, FiMessageCircle, FiUsers, FiHeart, FiTruck, FiGrid, FiHome,
    FiUser, FiCheckSquare, FiBook, FiBookOpen, FiVideo, FiLayers, FiArchive, FiAward, FiGlobe,
} from "react-icons/fi";

// Each entry drives one /products/prepschool/:slug page.
//   title        — short name, shown as the "old way" (problems) or in the breadcrumb
//   seoTitle     — the actual <h1>, written around the target keyword
//   metaTitle / metaDescription / keywords — <title>/<meta> tags (see useSEO)
//   mockup       — reuses a Mockups.jsx component as the page's visual; null = text-only layout
const details = [
    // ---------- Problems ----------
    {
        slug: "enquiries-lost-whatsapp-calls",
        category: "The Problem",
        tone: "red",
        icon: <FiFilter />,
        title: "Enquiries lost in WhatsApp & phone calls",
        seoTitle: "Preschool Enquiry & Admissions CRM Software — Stop Losing Leads",
        metaTitle: "Preschool Enquiry Management Software | PrepSchool",
        metaDescription: "Walk-ins and website leads quietly go cold with no funnel and no follow-up reminders. PrepSchool captures every enquiry into a tracked funnel automatically.",
        keywords: "preschool enquiry management software, admissions crm for preschools, playschool lead tracking software",
        lead: "No funnel, no follow-up reminders — walk-ins and website leads quietly go cold while front-desk staff juggle phone calls and WhatsApp chats.",
        sections: [
            { heading: "Every enquiry lands in one funnel, tagged by branch", body: "A website form fill, a walk-in, or an Instagram message all land in the same tracked funnel — New Enquiry, Visit Scheduled, Trial Class, Admitted or Waitlist — instead of scattered across a notebook and a phone's call log." },
            { heading: "Nothing goes untouched for more than a day", body: "Automatic follow-up reminders flag any enquiry that's gone quiet, so a front-desk team doesn't need to remember who they called last, or when." },
        ],
        bullets: [
            "Website enquiry widget captures leads — every form fill lands straight in the funnel, tagged by branch.",
            "Automatic follow-up reminders — no enquiry goes untouched for more than a day.",
            "Trial class to admission, in one click — convert a trial straight into an admission with fee auto-generated.",
            "Source & branch reporting — see which channel and campus converts best, every term.",
        ],
        mockup: "enquiry",
        stat: { value: "312", label: "enquiries tracked in one funnel view, in a typical term" },
        faqs: [
            { q: "Does every enquiry channel land in the same place?", a: "Yes — website forms, walk-ins and social channels all land in the same tracked funnel, tagged by branch and source." },
            { q: "How does PrepSchool stop an enquiry from going cold?", a: "Automatic follow-up reminders flag any enquiry that hasn't been touched in more than a day." },
            { q: "Can a trial class convert straight into an admission?", a: "Yes, in one click — the admission is created with the fee invoice auto-generated." },
        ],
    },
    {
        slug: "attendance-paper-register",
        category: "The Problem",
        tone: "red",
        icon: <FiCalendar />,
        title: "Attendance still runs on a paper register",
        seoTitle: "Digital Attendance & Verified Pickup Software for Preschools",
        metaTitle: "Preschool Attendance Software | PrepSchool",
        metaDescription: "A paper register has no proof of exactly who picked up which child, or when. PrepSchool logs check-in and verified pickup automatically.",
        keywords: "preschool attendance software, daycare pickup verification app, biometric attendance preschool",
        lead: "No proof of exactly who picked up which child, or when — a paper register can be signed by anyone, for anyone, at any time.",
        sections: [
            { heading: "Check-in that leaves a real record", body: "Front-desk staff mark drop-off in seconds via biometric, RFID or the app, and parents get an instant notification the moment their child is marked present." },
            { heading: "Pickup that actually checks who's collecting", body: "Only authorized guardians on file can collect a child — an OTP or photo match is required at the gate, so a pickup is never just a name spoken at the door." },
        ],
        bullets: [
            "Biometric, RFID or app check-in — front-desk staff mark drop-off in seconds, parents get an instant notification.",
            "Verified pickup, every time — only authorized guardians can collect a child, OTP or photo match required at the gate.",
            "Late pickup & absence, auto-flagged — front desk and parents both see the alert the moment a pattern breaks.",
            "Class-wise & branch-wise rollups — owners see attendance trends across every classroom and campus, live.",
        ],
        mockup: "attendance",
        faqs: [
            { q: "Can anyone claiming to be a guardian pick up a child?", a: "No — only guardians on file can collect a child, and an OTP or photo match is required at the gate." },
            { q: "Do parents know when their child is marked present?", a: "Yes, an instant notification goes out the moment front-desk staff mark the check-in." },
            { q: "What happens if a pickup is late or a child is absent?", a: "Both front desk and parents see the alert automatically, the moment the pattern breaks." },
        ],
    },
    {
        slug: "fee-collection-cash-memory",
        category: "The Problem",
        tone: "red",
        icon: <FiCreditCard />,
        title: "Fee collection by cash and memory",
        seoTitle: "Preschool Fee Management Software with Online Payments",
        metaTitle: "Preschool Fee Collection Software | PrepSchool",
        metaDescription: "Dues chased over phone calls and receipts written by hand don't scale. PrepSchool auto-generates invoices and collects online, with automatic reminders.",
        keywords: "preschool fee management software, daycare online fee payment, school fee reminder software",
        lead: "Dues chased over phone calls, receipts written out by hand every time — a process that depends entirely on someone remembering who still owes what.",
        sections: [
            { heading: "Invoices that bill themselves", body: "Term fees, transport charges and one-off costs generate automatically, so nobody manually re-enters the same fee structure every billing cycle." },
            { heading: "Reminders that go out before the awkward call", body: "SMS and WhatsApp nudges fire automatically before and after a due date, replacing the phone call a front-desk team would otherwise have to make." },
        ],
        bullets: [
            "Auto-generated invoices — term fees, transport and one-off charges billed without manual entry.",
            "Pay online in a tap — UPI, cards & net banking straight from the parent app.",
            "Automatic due reminders — SMS & WhatsApp nudges before and after a due date, no awkward calls.",
            "Receipts & ledgers, exportable — branded receipts and an accounting-ready ledger, one click.",
        ],
        mockup: "fee",
        stat: { value: "86%", label: "of billed fees collected on time in a typical term, once reminders are automatic" },
        faqs: [
            { q: "Do parents need to visit the school to pay fees?", a: "No, they can pay online in a tap via UPI, cards or net banking, directly from the parent app." },
            { q: "Does staff need to chase overdue fees by phone?", a: "No, automatic SMS and WhatsApp reminders go out before and after a due date." },
            { q: "Are receipts generated automatically?", a: "Yes, branded receipts and an accounting-ready ledger are available in one click." },
        ],
    },
    {
        slug: "parents-anxious-blind-to-day",
        category: "The Problem",
        tone: "red",
        icon: <FiMessageCircle />,
        title: "Parents left anxious, blind to the day",
        seoTitle: "Real-Time Digital Diary App for Preschools & Daycares",
        metaTitle: "Preschool Parent Communication App | PrepSchool",
        metaDescription: "No idea if their child ate, napped, or was in a good mood — until pickup. PrepSchool shares meals, naps and mood live, as the day happens.",
        keywords: "preschool digital diary app, daycare parent communication app, real time daycare updates",
        lead: "No idea if their child ate, napped, or was in a good mood — until pickup, when a rushed hand-off is the only update a parent gets all day.",
        sections: [
            { heading: "The day, shared as it happens", body: "Teachers log meals, naps, diaper changes and mood in seconds from the classroom, and photos reach parents the same minute they're taken — not as an end-of-day dump." },
            { heading: "One app, not five separate check-ins", body: "Parents see the live diary, notices, fees and attendance in a single app, with push, SMS and WhatsApp alerts on whichever channel they actually check." },
        ],
        bullets: [
            "Logged in seconds, per activity — teachers tap to record meals, naps, diaper changes and mood right from the classroom.",
            "Photos & short videos, shared instantly — parents see their child's moments the same minute they happen.",
            "Direct chat with teachers — parents message the classroom teacher directly, no group-chat noise.",
            "Push, SMS & WhatsApp alerts — critical updates reach parents on whichever channel they actually check.",
        ],
        mockup: "diary",
        faqs: [
            { q: "How often is the digital diary updated?", a: "As the day happens — teachers log each activity in seconds, and it reaches the parent app the same minute." },
            { q: "Can parents message the teacher directly?", a: "Yes, without a group chat, and without sharing personal phone numbers." },
            { q: "Is a child's diary visible to other parents?", a: "No, each child's diary is private by design — visible only to their own guardians and assigned teachers." },
        ],
    },
    {
        slug: "staff-records-scattered",
        category: "The Problem",
        tone: "red",
        icon: <FiUsers />,
        title: "Staff records scattered across registers",
        seoTitle: "Preschool Staff, HR & Payroll Software — One Record Per Teacher",
        metaTitle: "Preschool Staff & HR Software | PrepSchool",
        metaDescription: "Certificates, verification papers and shift rosters shouldn't live on paper. PrepSchool tracks staff attendance, roles and payroll in one place.",
        keywords: "preschool staff management software, daycare hr payroll software, teacher attendance app",
        lead: "Certificates, verification papers and shift rosters, all on paper — spread across registers that nobody can search when it actually matters.",
        sections: [
            { heading: "One record, every role scoped to what they need", body: "Owners and principals see full visibility across every branch and report, while teachers, admins and drivers each see only their own classroom, branch or route." },
            { heading: "Attendance that flows straight into payroll", body: "Staff check-in and shift rosters feed the payroll run directly, so a manager isn't reconciling a paper attendance sheet against a payroll spreadsheet every month." },
        ],
        bullets: [
            "Owner / Principal — full visibility across every branch, classroom and report; controls roles & billing.",
            "Admin / Front Desk — attendance, pickup verification, enquiries and fee collection for their branch.",
            "Teacher — digital diary, milestone tracking and curriculum for their own classroom only.",
            "Driver / Attendant — route roster, live GPS and boarding attendance from a dedicated transport app.",
        ],
        mockup: null,
        faqs: [
            { q: "Can a teacher see records from another classroom or branch?", a: "No, each role is scoped — a teacher sees only their own classroom, an admin only their own branch." },
            { q: "Does staff attendance feed payroll automatically?", a: "Yes, attendance and shift rosters flow directly into the payroll run." },
            { q: "Where are staff certificates and verification papers kept?", a: "In each staff member's own record on the platform, instead of a separate paper register." },
        ],
    },
    {
        slug: "child-health-history-memory",
        category: "The Problem",
        tone: "red",
        icon: <FiHeart />,
        title: "A child's health history lives in someone's memory",
        seoTitle: "Preschool Health, Safety & Medical Record Software",
        metaTitle: "Preschool Health & Safety Software | PrepSchool",
        metaDescription: "Allergies and medical notes shouldn't be word of mouth. PrepSchool surfaces allergy alerts and medical records to every relevant staff member automatically.",
        keywords: "preschool health safety software, daycare allergy alert system, immunization tracking software preschool",
        lead: "Allergies and medical notes aren't in a system — they're word of mouth, passed from one shift to the next and easy to miss on a busy day.",
        sections: [
            { heading: "A flag that's impossible to miss", body: "Allergy alerts appear on a child's profile, their diary and the classroom roster — kitchen staff, teachers and front desk all see the same real-time flag, for every meal, every day." },
            { heading: "Immunizations and incidents, tracked automatically", body: "Due and overdue vaccines are flagged term after term, and every fall or scrape is logged with time, photo and action taken, with parents notified instantly." },
        ],
        bullets: [
            "Medical records, per child — conditions, medications and doctor contacts, visible to authorized staff only.",
            "Immunization tracker — due & overdue vaccines flagged automatically, term after term.",
            "Allergy alerts, always visible — a red flag on the profile, the diary and the classroom roster.",
            "Incident & injury log — every fall or scrape logged with time, photo and action taken — parents notified instantly.",
        ],
        mockup: null,
        stat: { value: "0", label: "allergy alerts missed once every relevant staff member sees the same flag" },
        faqs: [
            { q: "Who can see a child's allergy or medical information?", a: "Authorized staff only — but the allergy flag itself appears everywhere it's relevant: the profile, the diary and the classroom roster." },
            { q: "How are immunization renewals tracked?", a: "Automatically — due and overdue vaccines are flagged term after term, before certificates lapse." },
            { q: "What happens after a fall or scrape at school?", a: "It's logged with time, photo and the action taken, and parents are notified instantly." },
        ],
    },
    {
        slug: "transport-black-box",
        category: "The Problem",
        tone: "red",
        icon: <FiTruck />,
        title: "Transport is a black box",
        seoTitle: "Live School Bus GPS Tracking App for Parents",
        metaTitle: "Preschool Transport Tracking Software | PrepSchool",
        metaDescription: "Parents don't know if the bus is late, or who's actually on board. PrepSchool gives live GPS tracking and RFID boarding logs from the app.",
        keywords: "school bus gps tracking app, daycare transport tracking software, rfid bus attendance system",
        lead: "Parents don't know if the bus is late, or who's actually on board — so every school run starts with a small dose of anxiety at the gate.",
        sections: [
            { heading: "The bus, visible in real time", body: "Parents track the bus live from the app instead of guessing at the gate, and a running-late bus pushes a revised pickup time before anyone has to ask." },
            { heading: "Boarding logged automatically, not assumed", body: "RFID tap-in and tap-out logs a child's boarding and alighting automatically, and the driver's own app carries the route roster, attendance and emergency contacts." },
        ],
        bullets: [
            "Live GPS on every route — parents track the bus in real time from the app, no more guessing at the gate.",
            "RFID tap-in, tap-out on board — a child's boarding and alighting is logged automatically, and parents are notified.",
            "Driver & attendant app — route stops, attendance and emergency contacts, all in the driver's own app.",
            "Delay & ETA alerts — running late? Parents get a push notification with a revised pickup time.",
        ],
        mockup: "transport",
        faqs: [
            { q: "Can parents see exactly where the bus is?", a: "Yes, live GPS tracking is visible from the parent app on every route." },
            { q: "How is a child's boarding recorded?", a: "Automatically, via RFID tap-in and tap-out as they get on and off the bus." },
            { q: "What happens if the bus is running late?", a: "Parents get a push notification with a revised pickup time, instead of finding out at the gate." },
        ],
    },
    {
        slug: "five-apps-dont-talk",
        category: "The Problem",
        tone: "red",
        icon: <FiGrid />,
        title: "Five apps, none of them talk",
        seoTitle: "All-In-One Preschool Management Platform — Replace Five Apps",
        metaTitle: "All-In-One Preschool Software | PrepSchool",
        metaDescription: "A fee app, an attendance app, a WhatsApp group and a spreadsheet, with no sync between them. PrepSchool runs everything on one platform instead.",
        keywords: "all in one preschool software, daycare management platform, replace multiple school apps",
        lead: "A fee app, an attendance app, a WhatsApp group and a spreadsheet — no sync, and no single place anyone can check for the full picture.",
        sections: [
            { heading: "One platform, not five subscriptions", body: "Admissions, attendance, fees, the digital diary, parent communication, curriculum, health & safety, transport and staff payroll all run on the same underlying student and family record." },
            { heading: "Nothing to reconcile between tools", body: "Because every module shares one record, a fee update, an attendance mark or a diary entry never needs to be re-entered somewhere else to stay in sync." },
        ],
        bullets: [
            "One vendor, one bill — no juggling five renewals and five support tickets.",
            "Nothing breaks in between — no API limits, sync failures or automation glue to babysit.",
            "Family data stays in one place — never scattered across five vendors' servers.",
            "One team accountable — Prepseed builds, hosts and supports all of it, no finger-pointing.",
        ],
        mockup: null,
        faqs: [
            { q: "Does PrepSchool replace a separate fee app and attendance app?", a: "Yes, admissions, attendance, fees, the diary and communication all run on one platform, sharing one student record." },
            { q: "What happens when something goes wrong across modules?", a: "There's one team accountable for all of it — Prepseed builds, hosts and supports the entire platform, not just one piece of it." },
            { q: "Is family data spread across multiple vendors' servers?", a: "No, it stays in one place, instead of scattered across five separate point-solution vendors." },
        ],
    },
    {
        slug: "owners-no-cross-branch-view",
        category: "The Problem",
        tone: "red",
        icon: <FiHome />,
        title: "Owners can't see across branches",
        seoTitle: "Multi-Branch Preschool Management Software with Franchise Console",
        metaTitle: "Multi-Branch Preschool Software | PrepSchool",
        metaDescription: "No consolidated view of enrollment, revenue or staff performance across campuses. PrepSchool rolls every branch up into one franchise console.",
        keywords: "multi branch preschool software, franchise preschool management software, preschool owner dashboard",
        lead: "No consolidated view of enrollment, revenue or staff performance — an owner running more than one campus is left stitching updates together by phone.",
        sections: [
            { heading: "Every branch, one console", body: "A single franchise console adds branches, replicates settings and rolls up enrollment, revenue and staff reports — without a separate login or spreadsheet per campus." },
            { heading: "Trends that surface without asking", body: "AI insights read the patterns across every branch automatically — a branch with dropping enquiries or a strong attendance streak surfaces on its own, in plain English." },
        ],
        bullets: [
            "Consolidated dashboard across all campuses and classrooms.",
            "Add branches and replicate settings from one console.",
            "Consolidated enrollment, revenue and staff reports.",
            "Per-branch fee structures, age groups and term calendars.",
        ],
        mockup: null,
        stat: { value: "50", label: "campuses supported on one platform, without re-platforming later" },
        faqs: [
            { q: "Can an owner see enrollment and revenue across every branch at once?", a: "Yes, a consolidated dashboard rolls up every campus and classroom into one view." },
            { q: "Does adding a new branch mean starting from scratch?", a: "No, settings replicate from the franchise console instead of being configured separately per branch." },
            { q: "Can each branch still have its own fee structure?", a: "Yes, fee structures, age groups and term calendars are configurable per branch." },
        ],
    },

    // ---------- Modules ----------
    {
        slug: "admissions-enquiry-crm",
        category: "Module",
        tone: "orange",
        icon: <FiFilter />,
        title: "Admissions & Enquiry CRM",
        seoTitle: "Preschool Admissions & Enquiry CRM Software",
        metaTitle: "Preschool Admissions CRM Software | PrepSchool",
        metaDescription: "Every enquiry, followed up — never dropped. Website leads, walk-ins and trial classes tracked in one funnel, with automatic follow-up reminders.",
        keywords: "preschool admissions crm software, playschool enquiry tracking software, admissions funnel software preschool",
        lead: "Every enquiry, followed up — never dropped. A website form fill lands straight in the funnel, tagged by branch, with automatic reminders so nothing goes untouched.",
        sections: [
            { heading: "One funnel, from first click to admission", body: "New Enquiry, Visit Scheduled, Trial Class, Admitted and Waitlist are all stages of the same funnel, so a lead never has to be re-entered as it moves from a website form to an actual seat." },
            { heading: "Reporting that shows what's actually working", body: "Source and branch reporting shows which channel and campus converts best each term, replacing guesswork about where marketing spend is actually paying off." },
        ],
        bullets: [
            "Website enquiry widget captures leads — every form fill lands straight in the funnel, tagged by branch.",
            "Automatic follow-up reminders — no enquiry goes untouched for more than a day.",
            "Trial class to admission, in one click — convert a trial straight into an admission with fee auto-generated.",
            "Source & branch reporting — see which channel and campus converts best, every term.",
        ],
        mockup: "enquiry",
        stat: { value: "142", label: "admitted students shown live in a typical funnel view" },
        faqs: [
            { q: "Does a website enquiry need to be re-typed into the CRM?", a: "No, the website enquiry widget feeds straight into the funnel automatically, tagged by branch and source." },
            { q: "Can a trial class convert directly into an admission?", a: "Yes, in one click, with the fee invoice generated automatically." },
            { q: "How does an owner know which marketing channel is working?", a: "Source & branch reporting shows conversion by channel and campus every term." },
        ],
    },
    {
        slug: "student-profiles-records",
        category: "Module",
        tone: "blue",
        icon: <FiUser />,
        title: "Student Profiles & Records",
        seoTitle: "Preschool Student Profile & Records Software",
        metaTitle: "Preschool Student Records Software | PrepSchool",
        metaDescription: "Every child's file, complete and current — photo, guardians, medical flags and documents in one always-current record.",
        keywords: "preschool student records software, daycare student profile app, child document vault software",
        lead: "Every child's file, complete and current. Photo, guardians, emergency contacts and documents live in a single record — with allergy flags surfaced, not buried.",
        sections: [
            { heading: "Critical information, surfaced not buried", body: "Allergy and medical flags appear directly on the profile itself, so they're visible at a glance instead of requiring someone to open a form nobody re-reads." },
            { heading: "Guardians with their own clear permissions", body: "Parents, grandparents or nannies can each be added as a guardian with their own pickup authorization, instead of one generic 'family contact' entry." },
        ],
        bullets: [
            "One file per child — photo, guardians, emergency contacts and documents in a single, always-current record.",
            "Allergy & medical flags, front and center — critical information surfaces on the profile, not buried in a form nobody re-reads.",
            "Multiple guardians, clear permissions — add parents, grandparents or nannies, each with their own pickup authorization.",
            "Document vault, always accessible — birth certificates, consent forms and immunization records, uploaded once and never lost.",
        ],
        mockup: "studentProfile",
        faqs: [
            { q: "Where do allergy flags show up?", a: "Directly on the child's profile, so they're visible at a glance rather than buried in a form." },
            { q: "Can more than one guardian be added per child?", a: "Yes, each guardian gets their own pickup authorization, rather than one shared family contact." },
            { q: "Are documents like birth certificates uploaded more than once?", a: "No, the document vault keeps them accessible after a single upload." },
        ],
    },
    {
        slug: "attendance-pickup-drop",
        category: "Module",
        tone: "green",
        icon: <FiCheckSquare />,
        title: "Attendance & Pickup-Drop",
        seoTitle: "Preschool Attendance & Verified Pickup Software",
        metaTitle: "Preschool Attendance & Pickup Software | PrepSchool",
        metaDescription: "Know who's in, and who's authorized to take them home. Biometric, RFID or app check-in with verified, OTP-gated pickup.",
        keywords: "preschool attendance software, verified child pickup app, biometric daycare check-in software",
        lead: "Know who's in, and who's authorized to take them home. Front-desk staff mark drop-off in seconds, and only verified guardians can collect a child.",
        sections: [
            { heading: "Check-in in seconds, not a signature", body: "Biometric, RFID or app-based check-in marks drop-off instantly, and parents get a notification the moment it happens — no paper register to sign." },
            { heading: "Pickup that's actually verified", body: "An OTP or photo match is required at the gate before a guardian can collect a child, and late pickups or absences are auto-flagged to both front desk and parents." },
        ],
        bullets: [
            "Biometric, RFID or app check-in — front-desk staff mark drop-off in seconds, parents get an instant notification.",
            "Verified pickup, every time — only authorized guardians can collect a child, OTP or photo match required at the gate.",
            "Late pickup & absence, auto-flagged — front desk and parents both see the alert the moment a pattern breaks.",
            "Class-wise & branch-wise rollups — owners see attendance trends across every classroom and campus, live.",
        ],
        mockup: "attendance",
        faqs: [
            { q: "How is drop-off attendance marked?", a: "Via biometric, RFID or the app, in seconds, with parents notified instantly." },
            { q: "Can someone without prior authorization pick up a child?", a: "No, an OTP or photo match against the guardians on file is required at the gate." },
            { q: "Do owners see attendance trends across branches?", a: "Yes, class-wise and branch-wise rollups are visible live." },
        ],
    },
    {
        slug: "digital-diary",
        category: "Module",
        tone: "orange",
        icon: <FiBook />,
        title: "Digital Diary",
        seoTitle: "Real-Time Digital Diary App for Preschools & Daycares",
        metaTitle: "Preschool Digital Diary Software | PrepSchool",
        metaDescription: "Meals, naps, diapers and mood — shared as the day happens, not as an end-of-day dump. Logged in seconds, private by design.",
        keywords: "preschool digital diary app, daycare activity log software, real time daycare updates app",
        lead: "Meals, naps, diapers and mood — shared as the day happens. Teachers log every activity in seconds, and parents see it the same minute it occurs.",
        sections: [
            { heading: "Logged from the classroom, in seconds", body: "A tap records a meal, a nap, a diaper change or a mood note right from the classroom, without pulling a teacher away from the children in front of them." },
            { heading: "A full day, private by design", body: "Every entry rolls up into a clean daily timeline a parent can revisit anytime, and each child's diary is visible only to their own guardians and assigned teachers." },
        ],
        bullets: [
            "Logged in seconds, per activity — teachers tap to record meals, naps, diaper changes and mood right from the classroom.",
            "Photos & short videos, shared instantly — parents see their child's moments the same minute they happen, no end-of-day dump.",
            "A full day, in one timeline — every entry rolls up into a clean daily report parents can look back on anytime.",
            "Private by design — each child's diary is visible only to their own guardians and assigned teachers.",
        ],
        mockup: "diary",
        stat: { value: "8", label: "activity entries shown live in a typical daily timeline" },
        faqs: [
            { q: "How quickly do diary entries reach a parent?", a: "The same minute they're logged — not batched into an end-of-day summary." },
            { q: "Can other parents see a different child's diary?", a: "No, each child's diary is private, visible only to their own guardians and assigned teachers." },
            { q: "Does logging a diary entry slow a teacher down?", a: "No, meals, naps, diaper changes and mood are all logged with a single tap from the classroom." },
        ],
    },
    {
        slug: "parent-communication-app",
        category: "Module",
        tone: "orange",
        icon: <FiMessageCircle />,
        title: "Parent Communication App",
        seoTitle: "Preschool Parent Communication App — Chat, Notices & Fees",
        metaTitle: "Preschool Parent Communication App | PrepSchool",
        metaDescription: "Every update, every notice — straight to the parent. Direct teacher chat, read-receipted notices, and live diary, fees and attendance in one app.",
        keywords: "preschool parent communication app, daycare parent app, school notice app with read receipts",
        lead: "Every update, every notice — straight to the parent. One app replaces group-chat noise with direct teacher chat and read-receipted notices.",
        sections: [
            { heading: "Direct chat, without the group-chat noise", body: "Parents message the classroom teacher directly, without personal phone numbers changing hands and without a hundred-parent group chat burying the one message that matters." },
            { heading: "Everything a parent needs, one login", body: "The live diary, fee payments, attendance and notices all sit inside a single app, reachable over push, SMS or WhatsApp — whichever channel a parent actually checks." },
        ],
        bullets: [
            "Direct chat with teachers — parents message the classroom teacher directly, no group-chat noise.",
            "Notices, circulars & event RSVPs — announcements reach every parent instantly, with read receipts for the school.",
            "Live diary, fees & attendance — everything a parent needs, in one app, no separate logins for separate tools.",
            "Push, SMS & WhatsApp alerts — critical updates reach parents on whichever channel they actually check.",
        ],
        mockup: "parentApp",
        faqs: [
            { q: "Do teachers have to share their personal phone number?", a: "No, parents chat directly with the classroom teacher inside the app, without exchanging personal numbers." },
            { q: "Does the school know if a notice was actually read?", a: "Yes, notices and circulars carry read receipts back to the school." },
            { q: "Does a parent need separate logins for fees, diary and attendance?", a: "No, all of it lives inside the same parent app." },
        ],
    },
    {
        slug: "fee-management-payments",
        category: "Module",
        tone: "green",
        icon: <FiCreditCard />,
        title: "Fee Management & Payments",
        seoTitle: "Preschool Fee Management Software with Auto Reminders",
        metaTitle: "Preschool Fee Management & Payments | PrepSchool",
        metaDescription: "Invoicing and collections, without the chasing. Auto-generated invoices, online payments and automatic due reminders.",
        keywords: "preschool fee management software, daycare online fee collection app, automatic fee reminder software",
        lead: "Invoicing and collections, without the chasing. Term fees, transport and one-off charges bill themselves, and reminders go out automatically.",
        sections: [
            { heading: "Bills that generate themselves", body: "Term fees, transport charges and one-off costs are billed without manual entry, and parents pay online in a tap via UPI, cards or net banking straight from the app." },
            { heading: "Reminders that replace the awkward call", body: "SMS and WhatsApp nudges go out automatically before and after a due date, and branded receipts plus an accounting-ready ledger are available in one click." },
        ],
        bullets: [
            "Auto-generated invoices — term fees, transport and one-off charges billed without manual entry.",
            "Pay online in a tap — UPI, cards & net banking straight from the parent app.",
            "Automatic due reminders — SMS & WhatsApp nudges before and after a due date, no awkward calls.",
            "Receipts & ledgers, exportable — branded receipts and an accounting-ready ledger, one click.",
        ],
        mockup: "fee",
        stat: { value: "74%", label: "of collections made online in a typical branch, once payments live in the parent app" },
        faqs: [
            { q: "Do parents have to visit the office to pay?", a: "No, payments can be made online in a tap, directly from the parent app." },
            { q: "Who sends the fee due reminders?", a: "The system does, automatically, over SMS and WhatsApp, before and after a due date." },
            { q: "Can fee ledgers be exported for accounting?", a: "Yes, branded receipts and an accounting-ready ledger export in one click." },
        ],
    },
    {
        slug: "curriculum-milestones",
        category: "Module",
        tone: "blue",
        icon: <FiBookOpen />,
        title: "Curriculum & Milestones",
        seoTitle: "Preschool Curriculum & Developmental Milestone Tracking Software",
        metaTitle: "Preschool Curriculum & Milestones Software | PrepSchool",
        metaDescription: "Weekly lesson plans, milestones tracked right behind them. A ready-made curriculum library with per-child developmental milestone tracking.",
        keywords: "preschool curriculum software, developmental milestone tracking app, daycare lesson plan software",
        lead: "Weekly lesson plans, milestones tracked right behind them. A ready-made curriculum library ships by age group, with milestones tracked as they're met.",
        sections: [
            { heading: "A curriculum library, not a blank page", body: "Weekly plans ship by age group and can be edited to fit a specific school, instead of every term starting from a blank lesson-planning document." },
            { heading: "Report cards built from real data", body: "Cognitive, motor, language and social-emotional markers are tracked per child, so term progress reports build themselves from actual milestone data instead of a term-end scramble." },
        ],
        bullets: [
            "Ready-made curriculum library — weekly plans by age group, edit to fit your school.",
            "Milestone tracking, per child — cognitive, motor, language and social-emotional markers.",
            "Report cards, generated fast — term progress reports built from real milestone data.",
            "Shared with parents, on schedule — weekly themes appear in the parent app automatically.",
        ],
        mockup: "curriculum",
        stat: { value: "68%", label: "of a term's milestones tracked live for a sample child" },
        faqs: [
            { q: "Does a school have to build its own curriculum from scratch?", a: "No, a ready-made curriculum library ships by age group and can be edited to fit the school." },
            { q: "What developmental areas are tracked?", a: "Cognitive, motor, language and social-emotional markers, per child." },
            { q: "Do report cards require manually compiling milestone notes?", a: "No, they generate from the milestone data that's already been tracked through the term." },
        ],
    },
    {
        slug: "health-safety-incident-management",
        category: "Module",
        tone: "red",
        icon: <FiHeart />,
        title: "Health, Safety & Incident Management",
        seoTitle: "Preschool Health, Safety & Incident Management Software",
        metaTitle: "Preschool Health & Safety Software | PrepSchool",
        metaDescription: "Every allergy, every incident — nothing falls through. Medical records, immunization tracking and allergy alerts visible in real time.",
        keywords: "preschool health safety software, daycare incident log software, immunization tracking preschool",
        lead: "Every allergy, every incident — nothing falls through. A missed allergy alert becomes a system failure, not a memory lapse.",
        sections: [
            { heading: "One flag, seen by everyone who needs it", body: "Kitchen staff, teachers and front desk all see the same real-time allergy flag — on the profile, the diary and the classroom roster — for every meal, every day." },
            { heading: "Immunizations and incidents, both tracked automatically", body: "Due and overdue vaccines are flagged term after term, and every fall or scrape is logged with time, photo and action taken, with parents notified instantly." },
        ],
        bullets: [
            "Medical records, per child — conditions, medications and doctor contacts, visible to authorized staff only.",
            "Immunization tracker — due & overdue vaccines flagged automatically, term after term.",
            "Allergy alerts, always visible — a red flag on the profile, the diary and the classroom roster, impossible to miss.",
            "Incident & injury log — every fall or scrape logged with time, photo and action taken, parents notified instantly.",
        ],
        mockup: null,
        faqs: [
            { q: "How is an allergy alert made impossible to miss?", a: "It appears as a red flag on the child's profile, their diary and the classroom roster, not just in one form." },
            { q: "Are immunization renewals tracked automatically?", a: "Yes, due and overdue vaccines are flagged term after term." },
            { q: "What's recorded after an incident like a fall?", a: "Time, photo and the action taken, with an instant notification to parents." },
        ],
    },
    {
        slug: "transport-gps-tracking",
        category: "Module",
        tone: "green",
        icon: <FiTruck />,
        title: "Transport & GPS Tracking",
        seoTitle: "Live School Bus GPS Tracking Software for Preschools",
        metaTitle: "Preschool Transport & GPS Tracking Software | PrepSchool",
        metaDescription: "The bus, visible to every parent, live. Live GPS, RFID boarding logs and automatic delay alerts with a revised pickup time.",
        keywords: "school bus gps tracking software, daycare transport app, rfid bus attendance preschool",
        lead: "The bus, visible to every parent, live. Parents track the bus in real time instead of guessing at the gate.",
        sections: [
            { heading: "Live tracking, not a guess", body: "Every route is visible from the parent app in real time, and a running-late bus pushes a revised pickup time automatically, before a parent has to call and ask." },
            { heading: "Boarding logged, not assumed", body: "RFID tap-in and tap-out logs a child's boarding and alighting automatically, while the driver's own app carries the route roster, attendance and emergency contacts." },
        ],
        bullets: [
            "Live GPS on every route — parents track the bus in real time from the app, no more guessing at the gate.",
            "RFID tap-in, tap-out on board — a child's boarding and alighting is logged automatically, and parents are notified.",
            "Driver & attendant app — route stops, attendance and emergency contacts, all in the driver's own app.",
            "Delay & ETA alerts — running late? Parents get a push notification with a revised pickup time.",
        ],
        mockup: "transport",
        faqs: [
            { q: "Can parents see the bus location in real time?", a: "Yes, live GPS tracking is available from the parent app on every route." },
            { q: "How is a child's boarding recorded on the bus?", a: "Automatically, through RFID tap-in and tap-out." },
            { q: "What happens if the bus runs late?", a: "Parents automatically get a push notification with a revised pickup time." },
        ],
    },
    {
        slug: "staff-hr-payroll",
        category: "Module",
        tone: "blue",
        icon: <FiUsers />,
        title: "Staff, HR & Payroll",
        seoTitle: "Preschool Staff, HR & Payroll Management Software",
        metaTitle: "Preschool Staff & Payroll Software | PrepSchool",
        metaDescription: "Every teacher's day, tracked — payroll made simple. Role-scoped access for owners, admins, teachers and drivers, with attendance feeding payroll directly.",
        keywords: "preschool hr payroll software, daycare staff attendance software, teacher payroll management app",
        lead: "Every teacher's day, tracked — payroll made simple. Attendance and roles feed straight into payroll, so month-end isn't a manual reconciliation.",
        sections: [
            { heading: "Every role, scoped to what it needs", body: "Owner/Principal sees full visibility across every branch; Admin/Front Desk handles their own branch's attendance and fees; Teacher sees only their own classroom; Driver/Attendant sees only their own route." },
            { heading: "Payroll that reads from real attendance", body: "Because staff check-in already lives on the platform, payroll reads from the same attendance record instead of a separately maintained spreadsheet." },
        ],
        bullets: [
            "Owner / Principal — full visibility across every branch, classroom and report; controls roles & billing.",
            "Admin / Front Desk — attendance, pickup verification, enquiries and fee collection for their branch.",
            "Teacher — digital diary, milestone tracking and curriculum for their own classroom only.",
            "Driver / Attendant — route roster, live GPS and boarding attendance from a dedicated transport app.",
        ],
        mockup: null,
        stat: { value: "64", label: "staff shown across branches in a typical payroll run" },
        faqs: [
            { q: "Can a teacher access another branch's staff records?", a: "No, every role is scoped — a teacher sees only their own classroom." },
            { q: "Does payroll require a separate attendance reconciliation?", a: "No, staff attendance feeds directly into the payroll run." },
            { q: "Does a driver need a separate app?", a: "They use a dedicated transport app scoped to their own route, roster and attendance." },
        ],
    },

    // ---------- Also built in ----------
    {
        slug: "cctv-live-streaming",
        category: "Also Built In",
        tone: "orange",
        icon: <FiVideo />,
        title: "CCTV & Live Streaming",
        seoTitle: "Built-In Classroom CCTV Live Streaming for Preschools",
        metaTitle: "Preschool CCTV Live Streaming | PrepSchool",
        metaDescription: "Live classroom streaming for verified parents, built into the same platform — no separate camera viewer app or subscription.",
        keywords: "preschool cctv live streaming software, classroom camera app for parents, daycare live video feed",
        lead: "Built-in live classroom streaming for verified parents — no separate camera app to install, and no extra subscription to manage.",
        sections: [
            { heading: "The same access controls as any other child record", body: "Live feeds are visible only to verified parents of enrolled children — CCTV access follows the same role-scoped rules that already protect every other piece of student data." },
            { heading: "One less standalone app to babysit", body: "There's no separate viewer app or extra subscription; classroom streaming is part of the same platform parents already use for the diary, fees and notices." },
        ],
        bullets: [
            "Live feeds visible only to verified parents of enrolled children.",
            "No standalone viewer app or extra subscription.",
            "Same access controls as every other child record.",
        ],
        mockup: null,
        faqs: [
            { q: "Can any parent view any classroom's feed?", a: "No, live feeds are visible only to verified parents of children enrolled in that specific classroom." },
            { q: "Is a separate app needed to watch the live feed?", a: "No, it's built into the same platform as the rest of PrepSchool." },
            { q: "Is CCTV access logged?", a: "Yes, it follows the same audit and access-control rules as every other child record." },
        ],
    },
    {
        slug: "multi-branch-management",
        category: "Also Built In",
        tone: "orange",
        icon: <FiLayers />,
        title: "Multi-Branch Management",
        seoTitle: "Multi-Branch & Franchise Preschool Management Console",
        metaTitle: "Multi-Branch Preschool Management | PrepSchool",
        metaDescription: "One franchise console rolls up every branch's settings, staff and reports — add branches and replicate settings without starting from scratch.",
        keywords: "multi branch preschool software, franchise preschool console, preschool owner reporting software",
        lead: "One franchise console rolls up every branch — settings, staff and reports, replicated or reviewed from a single dashboard.",
        sections: [
            { heading: "Adding a branch doesn't mean starting over", body: "Settings, fee structures and term calendars replicate from the franchise console, so a new campus doesn't need to be configured from a blank slate." },
            { heading: "Reports that roll up automatically", body: "Enrollment, revenue and staff performance consolidate across every branch, giving an owner one place to check instead of five separate branch logins." },
        ],
        bullets: [
            "Add branches and replicate settings from one console.",
            "Consolidated enrollment, revenue and staff reports.",
            "Per-branch fee structures, age groups and term calendars.",
        ],
        mockup: null,
        faqs: [
            { q: "Does every branch need its own separate configuration?", a: "No, settings replicate from a single franchise console." },
            { q: "Can fee structures differ by branch?", a: "Yes, fee structures, age groups and term calendars are configurable per branch." },
            { q: "Can an owner see all branches' performance in one view?", a: "Yes, enrollment, revenue and staff reports consolidate across every branch." },
        ],
    },
    {
        slug: "inventory-resources",
        category: "Also Built In",
        tone: "orange",
        icon: <FiArchive />,
        title: "Inventory & Resources",
        seoTitle: "Preschool Classroom Inventory & Supply Tracking Software",
        metaTitle: "Preschool Inventory & Resources Software | PrepSchool",
        metaDescription: "Classroom supplies, learning materials and equipment tracked per branch, so restocking isn't left to a manager's guesswork.",
        keywords: "preschool inventory management software, daycare supply tracking app, classroom resource management software",
        lead: "Classroom supplies, learning materials and equipment tracked per branch, so restocking isn't a manager's guesswork.",
        sections: [
            { heading: "Stock tracked where it's actually used", body: "Supplies and materials are tracked per classroom and branch, so a shortage is visible before it becomes a last-minute scramble before an activity." },
            { heading: "One shared record across every campus", body: "Low-stock alerts fire automatically, and the same inventory record is shared across every campus instead of a separate spreadsheet per branch." },
        ],
        bullets: [
            "Stock tracked per classroom and branch.",
            "Low-stock alerts before supplies run out.",
            "One record shared across every campus.",
        ],
        mockup: null,
        faqs: [
            { q: "Is inventory tracked per classroom or just per branch?", a: "Both — stock is tracked per classroom and rolls up to the branch level." },
            { q: "Does staff need to notice when supplies run low?", a: "No, low-stock alerts fire automatically before supplies run out." },
            { q: "Is there a separate inventory sheet per campus?", a: "No, one record is shared across every campus." },
        ],
    },
    {
        slug: "events-ptm-scheduling",
        category: "Also Built In",
        tone: "orange",
        icon: <FiCalendar />,
        title: "Events & PTM Scheduling",
        seoTitle: "Preschool Event & Parent-Teacher Meeting Scheduling Software",
        metaTitle: "Preschool Events & PTM Scheduling | PrepSchool",
        metaDescription: "Annual day, PTMs and field trips scheduled with RSVP tracking — including virtual PTMs over Zoom or Google Meet.",
        keywords: "preschool event scheduling software, parent teacher meeting scheduling app, daycare ptm rsvp tracking",
        lead: "Annual day, PTMs and field trips scheduled with RSVP tracking, so a headcount doesn't depend on a phone tree.",
        sections: [
            { heading: "RSVP tracking built into the notice itself", body: "Every event notice carries its own RSVP tracking, so a school knows who's attending without a separate phone-tree follow-up." },
            { heading: "Virtual PTMs, scheduled the same way", body: "Parent-teacher meetings can be scheduled over Zoom or Google Meet directly, with reminders sent automatically as the date nears." },
        ],
        bullets: [
            "RSVP tracking built into every event notice.",
            "Virtual PTM scheduling over Zoom or Google Meet.",
            "Reminders sent automatically as the date nears.",
        ],
        mockup: "attendance",
        faqs: [
            { q: "How does a school track who's coming to an event?", a: "RSVP tracking is built into the event notice itself, rather than a separate phone follow-up." },
            { q: "Can parent-teacher meetings be held virtually?", a: "Yes, PTMs can be scheduled over Zoom or Google Meet directly from the platform." },
            { q: "Do parents get reminded about an upcoming event?", a: "Yes, reminders send automatically as the event date nears." },
        ],
    },
    {
        slug: "alumni-certificates",
        category: "Also Built In",
        tone: "orange",
        icon: <FiAward />,
        title: "Alumni & Certificates",
        seoTitle: "Preschool Alumni Records & Certificate Generation Software",
        metaTitle: "Preschool Alumni & Certificates Software | PrepSchool",
        metaDescription: "Graduation certificates and alumni records generated and kept on file, long after a family moves on.",
        keywords: "preschool graduation certificate software, daycare alumni records app, school certificate generation software",
        lead: "Graduation certificates and alumni records generated and kept on file, long after a family moves on.",
        sections: [
            { heading: "Certificates from the record that's already there", body: "A graduation certificate generates directly from the child's existing student record, instead of a staff member re-typing their details into a separate template." },
            { heading: "A record that doesn't disappear at graduation", body: "Alumni contact history is kept after a child graduates, so a school can stay in touch without starting a new file from scratch." },
        ],
        bullets: [
            "Certificates generated from the student's own record.",
            "Alumni contact history kept after graduation.",
            "No re-typing a child's details a second time.",
        ],
        mockup: null,
        faqs: [
            { q: "Does staff need to re-enter a child's details to generate a certificate?", a: "No, the certificate generates directly from the student's existing record." },
            { q: "Is a family's information kept after graduation?", a: "Yes, alumni contact history is kept on file after a child graduates." },
            { q: "Is there a separate alumni database to maintain?", a: "No, it's part of the same platform as the rest of a student's record." },
        ],
    },
    {
        slug: "website-enquiry-widget",
        category: "Also Built In",
        tone: "orange",
        icon: <FiGlobe />,
        title: "Website Enquiry Widget",
        seoTitle: "Website Enquiry Widget for Preschool Admissions",
        metaTitle: "Preschool Website Enquiry Widget | PrepSchool",
        metaDescription: "A form embedded on the school's own website feeds straight into the Admissions & Enquiry CRM funnel, tagged by source.",
        keywords: "preschool website enquiry form, admissions widget for school website, daycare lead capture widget",
        lead: "A form embedded on the school's own website feeds straight into the Admissions & Enquiry CRM funnel, tagged by source.",
        sections: [
            { heading: "No enquiry re-typed from an email", body: "The widget embeds directly on a school's existing website, so a submission lands in the CRM funnel automatically instead of arriving as an email someone has to copy in by hand." },
            { heading: "Tagged from the moment it arrives", body: "Every submission is tagged by source and branch as it lands, so reporting on which page or campaign is converting doesn't require manual bookkeeping." },
        ],
        bullets: [
            "Embeds directly on your existing website.",
            "Every submission tagged by source and branch.",
            "No enquiry re-typed from an email into the CRM.",
        ],
        mockup: "enquiry",
        faqs: [
            { q: "Does the widget require rebuilding the school's website?", a: "No, it embeds directly on the existing website." },
            { q: "Is a submission's source tracked automatically?", a: "Yes, every submission is tagged by source and branch as it arrives." },
            { q: "Does staff need to manually copy enquiries from an inbox?", a: "No, submissions land straight in the Admissions & Enquiry CRM funnel." },
        ],
    },
];

export const detailsBySlug = details.reduce((acc, d) => {
    acc[d.slug] = d;
    return acc;
}, {});

export default details;
