import {
    FiRefreshCw, FiClock, FiCheckSquare, FiGrid, FiCreditCard, FiTag, FiUsers, FiDollarSign,
    FiTrendingUp, FiShield, FiStar, FiTool, FiGift, FiUserCheck, FiCpu, FiMessageCircle, FiMapPin,
} from "react-icons/fi";

// Each entry drives one /products/prepjewellery/:slug page.
//   title        — short name, shown as the "old way" (problems) or in the breadcrumb
//   seoTitle     — the actual <h1>, written around the target keyword
//   metaTitle / metaDescription / keywords — <title>/<meta> tags (see useSEO)
//   mockup       — reuses a Mockups.jsx component as the page's visual; null = text-only layout
const details = [
    // ---------- Problems ----------
    {
        slug: "purity-readings-copied-by-hand",
        category: "The Problem",
        tone: "red",
        icon: <FiRefreshCw />,
        title: "Purity readings copied by hand",
        seoTitle: "Automated Gold Purity Capture — No More Hand-Typed Readings",
        metaTitle: "Automated Gold Purity Capture Software | PrepJewellery ERP",
        metaDescription: "A transposed digit off the gold-testing machine changes what a store owes a customer. PrepJewellery ERP captures MaxSell purity readings straight into the ledger.",
        keywords: "gold purity capture software, maxsell integration jewellery erp, automated gold testing software, purity reading ledger sync",
        lead: "A transposed digit off the gold-testing machine changes what the store owes a customer — and a hand-typed reading is one keystroke away from being wrong.",
        sections: [
            {
                heading: "The reading never leaves the machine by hand",
                body: "PrepJewellery ERP connects directly to MaxSell XRF gold-testing machines — Karat Pro, Karat Prime and Aurum — so a purity reading is captured straight into the Old Metal Exchange and Purchase ledger the instant the scan completes.",
            },
            {
                heading: "Deviations route to a person, not a typo",
                body: "When a reading falls outside the declared purity's tolerance, it routes to manager approval instead of silently being keyed in as whatever number the counter believed it saw.",
            },
        ],
        bullets: [
            "MaxSell purity capture, built in — XRF readings feed straight into purchase intake.",
            "Audit-linked — every reading ties permanently to its transaction.",
            "Tolerance-gated — deviation from declared purity routes to manager approval.",
            "Hallmarking approval gate — stock release blocks automatically until HUID is captured.",
        ],
        mockup: "purchase",
        stat: { value: "0", label: "hand-retyped purity readings once MaxSell is connected" },
        faqs: [
            { q: "Which MaxSell machines does this connect to?", a: "Karat Pro, Karat Prime and Aurum — PrepJewellery ERP has a direct hardware link to all three." },
            { q: "What happens if a reading looks abnormal?", a: "It routes to manager approval instead of being accepted automatically, so a genuine outlier gets a human look before it affects a transaction." },
            { q: "Does this reading get recorded anywhere permanent?", a: "Yes, every MaxSell reading ties permanently to the transaction it was captured against, as part of the full audit trail." },
        ],
    },
    {
        slug: "gold-rate-updated-twice",
        category: "The Problem",
        tone: "red",
        icon: <FiClock />,
        title: "Gold rate updated twice",
        seoTitle: "Live Gold Rate Billing Software — One Update, Every Counter",
        metaTitle: "Live Gold Rate Billing Software | PrepJewellery ERP",
        metaDescription: "Stop updating the gold rate on paper and again in the register. PrepJewellery ERP refreshes every open bill at every counter the instant the rate changes.",
        keywords: "live gold rate billing software, gold rate sync jewellery software, jewellery pos gold rate update",
        lead: "Once on paper, again in the register — every counter, every morning. Two places to update the same number is two places it can drift out of sync.",
        sections: [
            {
                heading: "One rate, every counter, at once",
                body: "The day's gold rate is set once and refreshes every open bill across every counter and branch instantly — nobody re-enters it at the register or writes it on a board first.",
            },
            {
                heading: "Billing that can't run on yesterday's rate",
                body: "Because the rate lives in the same system that generates the bill, there's no window where a counter is quoting a rate that hasn't been updated yet.",
            },
        ],
        bullets: [
            "Live gold rate across every counter — one rate update refreshes every open bill in the store, instantly.",
            "Incentive wallet credits on every bill — no month-end spreadsheet — staff earnings post the moment a sale closes.",
            "Coupon rules enforced at billing — validity and redemption checked automatically, not by memory.",
            "GST billing built in, itemized against gold rate and making charges on every invoice.",
        ],
        mockup: "billing",
        stat: { value: "₹6,842/g", label: "a live 22K gold rate example, synced across every open bill" },
        faqs: [
            { q: "How many places does staff need to update the gold rate?", a: "One — the update refreshes every open bill at every counter instantly, with nothing to re-enter at the register." },
            { q: "Can two counters end up quoting different rates?", a: "No, because every counter reads the same live rate rather than a locally re-typed copy." },
            { q: "Does GST get calculated correctly against the live rate automatically?", a: "Yes, GST billing is itemized against the live gold rate and making charges on every invoice." },
        ],
    },
    {
        slug: "hallmarking-tracked-not-enforced",
        category: "The Problem",
        tone: "red",
        icon: <FiCheckSquare />,
        title: "Hallmarking tracked, not enforced",
        seoTitle: "HUID Hallmarking Approval Gate Software for Jewellery Stock",
        metaTitle: "Hallmarking Compliance Software | PrepJewellery ERP",
        metaDescription: "A paper checklist doesn't stop non-compliant stock reaching the shelf. PrepJewellery ERP blocks stock release automatically until HUID is captured.",
        keywords: "huid hallmarking software, hallmarking compliance jewellery erp, hallmark approval gate software",
        lead: "A paper checklist doesn't stop non-compliant stock from reaching the shelf — it only records, after the fact, that someone was supposed to check.",
        sections: [
            {
                heading: "A gate in the software, not a box on a form",
                body: "Stock release blocks automatically until the item's HUID is captured on file — there's no way for a piece to clear into sellable inventory by skipping the step, because the system itself enforces the order of operations.",
            },
            {
                heading: "The same gate purity readings pass through",
                body: "MaxSell purity capture and HUID hallmarking share the same stock-release gate, so both quality checks are enforced together rather than as two separate, easily-skipped procedures.",
            },
        ],
        bullets: [
            "Hallmarking approval gate — stock release blocks automatically until HUID is captured.",
            "Multi-stage delivery challan flow — DCs, purchase invoices and credit notes tracked end to end.",
            "MaxSell purity capture, built in — XRF readings feed straight into purchase intake.",
            "Vendor scorecards, auto-updated — QC outcomes and returns score every supplier automatically.",
        ],
        mockup: "purchase",
        faqs: [
            { q: "Can stock be sold before its HUID is on file?", a: "No, the stock-release gate blocks it automatically until HUID is captured — it isn't left to a manual checklist." },
            { q: "Does this also cover purity, or only HUID?", a: "Both — MaxSell purity capture shares the same release gate as HUID hallmarking." },
            { q: "How are vendors scored on hallmarking and QC outcomes?", a: "Vendor scorecards update automatically from QC outcomes and returns, so supplier reliability is visible without a manual review." },
        ],
    },
    {
        slug: "reorder-by-walking-shelves",
        category: "The Problem",
        tone: "red",
        icon: <FiGrid />,
        title: "Reorder by walking the shelves",
        seoTitle: "Automatic Reorder Alerts for Multi-Branch Jewellery Inventory",
        metaTitle: "Jewellery Reorder Alert Software | PrepJewellery ERP",
        metaDescription: "Low stock shouldn't depend on a manager's eye. PrepJewellery ERP fires reorder alerts by product and branch the moment stock crosses the minimum.",
        keywords: "jewellery reorder alert software, multi branch inventory software, low stock alert jewellery erp",
        lead: "Low stock is spotted by a manager's eye, not by the system — which means it's spotted late, or missed on the branch nobody walked that week.",
        sections: [
            {
                heading: "Alerts fire before the shelf actually goes empty",
                body: "The Reorder Dashboard raises an alert by product and branch automatically the moment stock crosses its configured minimum, instead of waiting for someone to notice a gap on the shelf.",
            },
            {
                heading: "Transfers between branches post themselves",
                body: "When stock moves between branches to cover a shortfall, the transfer posts with matching accounting entries at both ends automatically, so a physical move doesn't leave the books out of sync.",
            },
        ],
        bullets: [
            "Reorder Dashboard, automatic — alerts fire by product and branch the moment stock crosses the minimum.",
            "Stock transfers post themselves — matching accounting entries land at both branches automatically.",
            "Physical verification locks stock — no silent adjustments until variance is signed off.",
            "Diamond QC workflow gated — issue-to-karigar waits on recorded approval.",
        ],
        mockup: "inventory",
        stat: { value: "14", label: "low-stock SKUs flagged automatically in a typical 4-branch catalog" },
        faqs: [
            { q: "How does the system know when to raise a reorder alert?", a: "Each product and branch has a configured minimum, and an alert fires automatically the moment stock crosses it." },
            { q: "What happens when stock moves between branches?", a: "The transfer posts with matching accounting entries at both branches automatically, instead of needing a manual journal entry." },
            { q: "Can stock be adjusted without anyone noticing?", a: "No, physical verification locks stock, and silent adjustments aren't possible until a variance is formally signed off." },
        ],
    },
    {
        slug: "incentives-on-spreadsheet",
        category: "The Problem",
        tone: "red",
        icon: <FiCreditCard />,
        title: "Incentives on a spreadsheet",
        seoTitle: "Automatic Sales Incentive Wallet Software for Jewellery Counters",
        metaTitle: "Jewellery Sales Incentive Software | PrepJewellery ERP",
        metaDescription: "Sales staff earnings shouldn't be reconciled by hand once a month. PrepJewellery ERP credits the incentive wallet the moment a qualifying bill closes.",
        keywords: "jewellery sales incentive software, staff incentive wallet software, sales commission automation jewellery",
        lead: "Sales staff earnings reconciled by hand, once a month, means staff wait weeks to see what they actually earned — and disputes surface only after the fact.",
        sections: [
            {
                heading: "Earnings post the moment the sale closes",
                body: "The incentive wallet credits automatically on every qualifying bill, the instant it closes at the counter, rather than waiting for someone to reconcile a month's worth of sales against a spreadsheet.",
            },
            {
                heading: "The same wallet feeds payroll directly",
                body: "Because incentives already live in the wallet by the time payroll runs, sales-floor earnings from billing credit straight into the payroll run — it isn't a second reconciliation exercise.",
            },
        ],
        bullets: [
            "Incentive wallet credits on every bill — no month-end spreadsheet — staff earnings post the moment a sale closes.",
            "Incentive wallet feeds the payroll run — sales-floor earnings from Sales & POS credit automatically.",
            "Live gold rate across every counter — one rate update refreshes every open bill in the store, instantly.",
            "Coupon rules enforced at billing — validity and redemption checked automatically, not by memory.",
        ],
        mockup: "billing",
        stat: { value: "₹4,120", label: "a typical live incentive wallet balance, credited without a spreadsheet" },
        faqs: [
            { q: "When does a staff member's incentive actually post?", a: "The moment the qualifying bill closes at the counter — not at month-end." },
            { q: "Does this feed into payroll automatically?", a: "Yes, the incentive wallet feeds the payroll run directly, so it isn't reconciled separately." },
            { q: "Can staff see their own incentive balance?", a: "Yes, the wallet balance is visible live, rather than only surfacing once a month." },
        ],
    },
    {
        slug: "is-my-repair-ready",
        category: "The Problem",
        tone: "red",
        icon: <FiTag />,
        title: "\"Is my repair ready?\"",
        seoTitle: "Public Repair Status Tracking Software for Jewellery Stores",
        metaTitle: "Jewellery Repair Tracking Software | PrepJewellery ERP",
        metaDescription: "Customers call the store because there's nowhere else to check a repair's status. PrepJewellery ERP gives them a public tracking link instead.",
        keywords: "jewellery repair tracking software, repair status portal jewellery, whatsapp repair status alerts",
        lead: "Customers call the store because there's nowhere else to check — and every one of those calls pulls a staff member off the counter to go look something up.",
        sections: [
            {
                heading: "A public link shows the exact same status the counter sees",
                body: "A repair's status — intake, in service, ready for pickup, picked up — is visible on a public tracking link with no login required, so a customer can check it themselves instead of calling.",
            },
            {
                heading: "WhatsApp closes the loop without a phone call either way",
                body: "A WhatsApp message fires automatically at intake and again when the repair is ready for pickup, so the customer is told before they'd think to ask.",
            },
        ],
        bullets: [
            "WhatsApp sent at intake and at ready-for-pickup — the customer is notified automatically, both times.",
            "Public tracking link, no login required — the customer sees the exact same status the counter does.",
            "No staff callback needed — a repair's status is always self-serve, not dependent on someone picking up the phone.",
        ],
        mockup: "repairs",
        stat: { value: "0", label: "phone calls required to check a repair's live status" },
        faqs: [
            { q: "Does a customer need to log in to check repair status?", a: "No, the tracking link is public — no login or account is required." },
            { q: "How does a customer find out a repair is ready without calling?", a: "A WhatsApp message fires automatically the moment the repair is marked ready for pickup." },
            { q: "Is the public tracking status the same one staff see internally?", a: "Yes, it's the exact same status the counter sees — there's no separate, delayed customer-facing view." },
        ],
    },
    {
        slug: "walk-ins-never-followed-up",
        category: "The Problem",
        tone: "red",
        icon: <FiUsers />,
        title: "Walk-ins never followed up",
        seoTitle: "Automatic Walk-In Follow-Up Software for Jewellery CRM",
        metaTitle: "Jewellery Walk-In Follow-Up Software | PrepJewellery ERP",
        metaDescription: "A thank-you or a nudge shouldn't depend on staff remembering. PrepJewellery ERP fires a follow-up WhatsApp on every walk-in, automatically.",
        keywords: "jewellery walk-in follow up software, jewellery crm automation, whatsapp thank you walk-in",
        lead: "A thank-you or a nudge depends entirely on staff remembering — and on a busy Saturday, remembering to follow up on Tuesday's walk-in is the first thing that slips.",
        sections: [
            {
                heading: "The thank-you fires the moment the visit is logged",
                body: "A thank-you WhatsApp goes out automatically as soon as a walk-in is logged at the counter — no staff member needs to remember to send anything afterwards.",
            },
            {
                heading: "Interest shown at the counter starts its own follow-up",
                body: "When a customer shows interest in a specific piece, a follow-up pipeline reminder triggers based on their segment and how long it's been since that interest was shown, rather than relying on memory.",
            },
        ],
        bullets: [
            "Thank-you WhatsApp on every walk-in — fires the moment a visit is logged, no staff action needed.",
            "Proposals generate & send themselves — PDF proposal over WhatsApp on creation.",
            "Follow-up pipeline reminders — triggered by segment and time elapsed since interest was shown.",
        ],
        mockup: "crm",
        stat: { value: "₹4.1L", label: "typical lifetime value visible per repeat customer profile" },
        faqs: [
            { q: "Does someone have to remember to send a thank-you message?", a: "No, it fires automatically the moment the walk-in is logged." },
            { q: "How does a proposal get to the customer?", a: "It generates and sends itself as a PDF over WhatsApp the moment it's created." },
            { q: "What triggers a follow-up reminder?", a: "The customer's segment and the time elapsed since they showed interest — not a staff member's memory." },
        ],
    },
    {
        slug: "bank-statements-matched-by-hand",
        category: "The Problem",
        tone: "red",
        icon: <FiDollarSign />,
        title: "Bank statements matched by hand",
        seoTitle: "Automated Bank Reconciliation Software for Jewellery Accounts",
        metaTitle: "Jewellery Bank Reconciliation Software | PrepJewellery ERP",
        metaDescription: "Reconciliation shouldn't happen line by line at month-end. PrepJewellery ERP auto-matches bank lines against vouchers, flagging only genuine exceptions.",
        keywords: "jewellery bank reconciliation software, automated accounts reconciliation, gold shop accounting software",
        lead: "Reconciliation happens line by line, at month-end — a job that eats hours and still leaves room for a missed mismatch nobody catches until it's too late to fix easily.",
        sections: [
            {
                heading: "Matching happens continuously, not once a month",
                body: "Bank lines auto-match against vouchers as transactions happen, so by month-end there's a short list of genuine exceptions to review rather than an entire statement to reconcile from scratch.",
            },
            {
                heading: "A full double-entry system underneath",
                body: "Chart of Accounts, vouchers, cashbook and ledgers sit underneath every module, so a bank line has something concrete and current to match against instead of a manually-maintained parallel record.",
            },
        ],
        bullets: [
            "Bank lines auto-matched — only genuine exceptions need a human look.",
            "TDS & gold revaluation, automatic — entries post against the day's transactions and rate.",
            "Full double-entry system — Chart of Accounts, vouchers, cashbook and ledgers underneath every module.",
            "Ageing analysis refreshes continuously — not just when someone asks for it.",
        ],
        mockup: "accounts",
        stat: { value: "Auto", label: "bank lines matched against vouchers, exceptions flagged for review" },
        faqs: [
            { q: "How often does bank reconciliation happen?", a: "Continuously — bank lines match against vouchers as transactions occur, rather than only at month-end." },
            { q: "What still needs a manual look?", a: "Only genuine exceptions — lines that don't match any recorded voucher — need a human review." },
            { q: "Does gold revaluation get entered manually?", a: "No, TDS and gold revaluation entries post automatically against the day's transactions and rate." },
        ],
    },
    {
        slug: "dc-cancellations-no-trail",
        category: "The Problem",
        tone: "red",
        icon: <FiCheckSquare />,
        title: "DC cancellations, no trail",
        seoTitle: "Auditable Delivery Challan Cancellation Software for Jewellery",
        metaTitle: "DC Cancellation Audit Trail Software | PrepJewellery ERP",
        metaDescription: "A verbal manager sign-off leaves nothing to audit later. PrepJewellery ERP requires a WhatsApp OTP to an authorised manager, logged, to cancel a DC.",
        keywords: "delivery challan cancellation software, jewellery purchase audit trail, dc cancellation otp jewellery erp",
        lead: "A verbal manager sign-off leaves nothing to audit later — if a delivery challan gets cancelled, there's no record of who actually approved it or why.",
        sections: [
            {
                heading: "A DC cancellation needs an OTP, not a nod",
                body: "Cancelling a delivery challan requires a WhatsApp OTP sent to an authorised manager on request — the cancellation can't happen on a verbal say-so, and the request itself is logged.",
            },
            {
                heading: "Part of the same full audit trail as everything else",
                body: "The cancellation, the OTP request and the manager who approved it are all recorded as part of the platform's full audit trail — every automated action logged, not just user edits.",
            },
        ],
        bullets: [
            "Multi-stage delivery challan flow — DCs, purchase invoices and credit notes tracked end to end.",
            "Purchase DC Cancel OTP sent over WhatsApp — on request, to an authorised manager.",
            "Every automated action logged, not just user edits.",
            "Approval gates in code, not a paper checklist.",
        ],
        mockup: "purchase",
        faqs: [
            { q: "Can a DC be cancelled without any approval?", a: "No, cancellation requires a WhatsApp OTP sent to an authorised manager — it can't happen on a verbal sign-off." },
            { q: "Is there a record of who cancelled a DC and when?", a: "Yes, the cancellation, the OTP request and the approving manager are all part of the full audit trail." },
            { q: "Does this slow down a legitimate cancellation?", a: "No, the OTP goes out on request over WhatsApp — it's a gate, not a multi-day approval process." },
        ],
    },

    // ---------- Modules ----------
    {
        slug: "sales-pos",
        category: "Module",
        tone: "gold",
        icon: <FiTrendingUp />,
        title: "Sales & POS",
        seoTitle: "Jewellery POS Software — Live Gold Rate, GST Billing & Incentives",
        metaTitle: "Jewellery Sales & POS Software | PrepJewellery ERP",
        metaDescription: "Live gold rate, GST billing, and incentives that credit themselves — every counter, on the same automation engine.",
        keywords: "jewellery pos software, gold rate billing software, gst jewellery billing software, sales incentive wallet jewellery",
        lead: "Live gold rate, GST billing, and incentives that credit themselves. Every counter runs on the same rate, and every qualifying bill credits the sales incentive wallet the moment it closes.",
        sections: [
            {
                heading: "Billing that never runs on a stale rate",
                body: "One gold-rate update refreshes every open bill across every counter in the store instantly, so a customer at counter three is never quoted a different rate than counter one.",
            },
            {
                heading: "Incentives, coupons and returns, handled at the point of sale",
                body: "The incentive wallet, coupon validity and sale-return confirmations are all enforced or triggered directly from the billing screen — nothing is a separate step done later.",
            },
        ],
        bullets: [
            "Live gold rate across every counter — one rate update refreshes every open bill in the store, instantly.",
            "Incentive wallet credits on every bill — no month-end spreadsheet — staff earnings post the moment a sale closes.",
            "Coupon rules enforced at billing — validity and redemption checked automatically, not by memory.",
            "Sale returns confirm over WhatsApp — a refund triggers an automatic customer confirmation.",
        ],
        mockup: "billing",
        stat: { value: "₹6,842/g", label: "a live gold rate, synced across every counter in the store" },
        faqs: [
            { q: "How quickly does a gold rate change reach every counter?", a: "Instantly — one update refreshes every open bill across every counter and branch." },
            { q: "When do sales incentives get credited?", a: "The moment a qualifying bill closes, into a live incentive wallet — not reconciled monthly." },
            { q: "What happens when a sale is returned?", a: "The refund triggers an automatic WhatsApp confirmation to the customer." },
        ],
    },
    {
        slug: "purchase-hallmarking",
        category: "Module",
        tone: "gold",
        icon: <FiShield />,
        title: "Purchase & Hallmarking",
        seoTitle: "Purchase & Hallmarking Software — HUID Approval Gate for Jewellery",
        metaTitle: "Jewellery Purchase & Hallmarking Software | PrepJewellery ERP",
        metaDescription: "Stock doesn't reach the shelf until HUID and purity are on file — a release gate enforced in software, not left to memory.",
        keywords: "jewellery purchase software, huid hallmarking software, vendor scorecard jewellery erp, dc purchase software",
        lead: "Stock doesn't reach the shelf until HUID and purity are on file. A delivery challan can't clear into sellable stock until quality, hallmarking and purity are all confirmed.",
        sections: [
            {
                heading: "Every DC moves through the same stages, every time",
                body: "Delivery challans, purchase invoices and credit notes are tracked end to end through the same multi-stage flow, so nothing skips QC, hallmarking or purity capture on the way to becoming sellable stock.",
            },
            {
                heading: "Suppliers scored on what actually happened",
                body: "Vendor scorecards update automatically from QC outcomes and returns, so a supplier's reliability is visible from real data rather than from whoever remembers the last delivery.",
            },
        ],
        bullets: [
            "Multi-stage delivery challan flow — DCs, purchase invoices and credit notes tracked end to end.",
            "Hallmarking approval gate — stock release blocks automatically until HUID is captured.",
            "MaxSell purity capture, built in — XRF readings feed straight into purchase intake.",
            "Vendor scorecards, auto-updated — QC outcomes and returns score every supplier automatically.",
        ],
        mockup: "purchase",
        stat: { value: "92", label: "an example vendor score, calculated automatically from QC and delivery outcomes" },
        faqs: [
            { q: "Can a delivery challan's stock be sold before hallmarking is confirmed?", a: "No, the stock-release gate blocks it automatically until HUID is captured on file." },
            { q: "How is purity captured during purchase intake?", a: "MaxSell XRF readings feed straight into purchase intake, so purity is on file without manual entry." },
            { q: "How are vendors scored?", a: "Automatically, from QC outcomes and returns — the scorecard updates itself rather than requiring a manual review." },
        ],
    },
    {
        slug: "inventory",
        category: "Module",
        tone: "blue",
        icon: <FiGrid />,
        title: "Inventory",
        seoTitle: "Multi-Branch Jewellery Inventory Software with Reorder Alerts",
        metaTitle: "Jewellery Inventory Software | PrepJewellery ERP",
        metaDescription: "Stock that reorders before a shelf goes empty — multi-branch stock visibility with automatic reorder alerts by product and branch.",
        keywords: "jewellery inventory software, multi branch stock software, reorder alert jewellery erp, diamond qc workflow software",
        lead: "Stock that reorders before a shelf goes empty. Reorder alerts fire by product and branch the moment stock crosses its minimum — no manager needs to walk the shelves to find out.",
        sections: [
            {
                heading: "Every branch's stock, one dashboard",
                body: "Stock across every branch is visible in one dashboard, with reorder thresholds tracked per product and per branch instead of relying on someone physically checking the shelf.",
            },
            {
                heading: "Transfers, verification and diamond QC, all gated",
                body: "Stock transfers post their own accounting entries at both branches, physical verification locks stock against silent adjustment, and issuing diamonds to a karigar waits on a recorded QC approval.",
            },
        ],
        bullets: [
            "Reorder Dashboard, automatic — alerts fire by product and branch the moment stock crosses the minimum.",
            "Stock transfers post themselves — matching accounting entries land at both branches automatically.",
            "Physical verification locks stock — no silent adjustments until variance is signed off.",
            "Diamond QC workflow gated — issue-to-karigar waits on recorded approval.",
        ],
        mockup: "inventory",
        stat: { value: "3,412", label: "SKUs tracked live across a typical multi-branch catalog" },
        faqs: [
            { q: "How is a reorder threshold set?", a: "Per product and per branch — an alert fires automatically the moment stock crosses that configured minimum." },
            { q: "What happens when stock is transferred between branches?", a: "Matching accounting entries post at both branches automatically, alongside the physical transfer." },
            { q: "Can diamonds be issued to a karigar without a QC check?", a: "No, the diamond QC workflow gates that step until an approval is recorded." },
        ],
    },
    {
        slug: "manufacturing",
        category: "Module",
        tone: "gold",
        icon: <FiStar />,
        title: "Manufacturing",
        seoTitle: "Jewellery Manufacturing Software — BOM to Finished Piece",
        metaTitle: "Jewellery Manufacturing Software | PrepJewellery ERP",
        metaDescription: "Bill of Materials to finished piece — metal flow reconciled at every stage, for both B2B and B2C manufacturing orders.",
        keywords: "jewellery manufacturing software, bom jewellery erp, metal flow reconciliation software, b2b b2c jewellery orders",
        lead: "Bill of Materials to finished piece — metal flow reconciled at every stage. A manufacturing job opens against a BOM and closes only once metal issued matches metal returned, cast and finished.",
        sections: [
            {
                heading: "A job opens with its accounting already correct",
                body: "Material issue posts automatically from the Bill of Materials the moment a manufacturing job opens, so there's no separate journal entry to remember to make afterwards.",
            },
            {
                heading: "One pipeline, whether the order is B2B or B2C",
                body: "The same manufacturing pipeline — wax, casting, finishing, QC and stock-in — handles both B2B and B2C orders, with job-stage notifications firing automatically as a piece moves through it.",
            },
        ],
        bullets: [
            "Material issue auto-posts from BOM — no manual journal entry when a job opens.",
            "B2B & B2C order management — same manufacturing pipeline, either order type.",
            "Karigar job-stage notifications — status changes trigger automatic alerts.",
            "Metal flow reconciles continuously — not a year-end exercise anymore.",
        ],
        mockup: "manufacturing",
        stat: { value: "5", label: "BOM-to-stock stages tracked automatically on a typical manufacturing job" },
        faqs: [
            { q: "Does opening a manufacturing job require a manual accounting entry?", a: "No, material issue posts automatically from the Bill of Materials the moment the job opens." },
            { q: "Can the same pipeline handle both custom (B2C) and bulk (B2B) orders?", a: "Yes, both order types run through the same manufacturing pipeline." },
            { q: "How often does metal flow get reconciled?", a: "Continuously, as the job moves through stages — not as a year-end exercise." },
        ],
    },
    {
        slug: "karigar-management",
        category: "Module",
        tone: "green",
        icon: <FiTool />,
        title: "Karigar Management",
        seoTitle: "Karigar Ledger & Settlement Software for Jewellery Manufacturing",
        metaTitle: "Karigar Management Software | PrepJewellery ERP",
        metaDescription: "The ledger between store and artisan settles itself — karigar ledgers, service charges and process milestones, calculated automatically.",
        keywords: "karigar management software, karigar ledger settlement software, jewellery artisan ledger jewellery erp",
        lead: "The ledger between store and artisan settles itself. Metal issued to a karigar and metal received back reconcile continuously — not just when a job finally comes back to the store.",
        sections: [
            {
                heading: "Settlement calculated from real weights, not a notebook",
                body: "The karigar ledger settles based directly on issued-versus-received weights, and service charges calculate automatically by weight and job type on completion, replacing a running notebook tally.",
            },
            {
                heading: "Accountability that doesn't wait for handover",
                body: "Issued and received entries reconcile as work actually moves, with every process milestone timestamped against the karigar — metal accountability is real-time, not something checked only when the job returns.",
            },
        ],
        bullets: [
            "Karigar ledger, auto-settled — calculated straight from issued vs. received weights.",
            "Service charges auto-calculated — by weight and job type, on job completion.",
            "Metal accountability, real time — issued and received entries reconcile as work moves, not at handover.",
            "Process milestones recorded — every stage of a job timestamped against the karigar.",
        ],
        mockup: "karigar",
        stat: { value: "3", label: "karigars shown reconciled live in a typical ledger view" },
        faqs: [
            { q: "How is a karigar's ledger settled?", a: "Automatically, calculated from issued-versus-received weights — not manually tallied." },
            { q: "When are service charges calculated?", a: "On job completion, by weight and job type, calculated automatically." },
            { q: "Is metal accountability checked only when a job comes back?", a: "No, issued and received entries reconcile continuously as work moves, in real time." },
        ],
    },
    {
        slug: "crm-customer",
        category: "Module",
        tone: "gold",
        icon: <FiUsers />,
        title: "CRM & Customer",
        seoTitle: "Jewellery CRM Software — Walk-Ins, Proposals & Loyalty",
        metaTitle: "Jewellery CRM Software | PrepJewellery ERP",
        metaDescription: "Every walk-in remembered — and followed up automatically. Thank-you WhatsApp, self-sending proposals and follow-up reminders, all automatic.",
        keywords: "jewellery crm software, walk-in follow up automation, jewellery proposal software, customer loyalty jewellery erp",
        lead: "Every walk-in remembered — and followed up automatically. A visit, a proposal or an interest shown at the counter starts its own automatic follow-up sequence.",
        sections: [
            {
                heading: "Nothing depends on staff remembering",
                body: "A thank-you WhatsApp fires the moment a visit is logged, and a proposal generates and sends itself as a PDF the moment it's created — the counter doesn't have to remember to do either afterward.",
            },
            {
                heading: "Follow-up that matches how interested a customer actually is",
                body: "Follow-up pipeline reminders trigger based on customer segment and how long it's been since interest was shown, so a serious prospect doesn't go quiet just because nobody happened to think of them that week.",
            },
        ],
        bullets: [
            "Thank-you WhatsApp on every walk-in — fires the moment a visit is logged, no staff action needed.",
            "Proposals generate & send themselves — PDF proposal over WhatsApp on creation.",
            "Follow-up pipeline reminders — triggered by segment and time elapsed since interest was shown.",
        ],
        mockup: "crm",
        stat: { value: "₹4.1L", label: "typical lifetime value visible on a single customer profile" },
        faqs: [
            { q: "Does every walk-in get a thank-you message?", a: "Yes, automatically, the moment the visit is logged at the counter." },
            { q: "How does a customer receive a proposal?", a: "As a PDF sent over WhatsApp automatically the moment the proposal is created." },
            { q: "What decides when a follow-up reminder goes out?", a: "The customer's segment and the time elapsed since they showed interest, not a staff member remembering." },
        ],
    },
    {
        slug: "savings-schemes",
        category: "Module",
        tone: "green",
        icon: <FiGift />,
        title: "Savings Schemes",
        seoTitle: "Gold Savings Scheme Software with Razorpay Reconciliation",
        metaTitle: "Jewellery Savings Scheme Software | PrepJewellery ERP",
        metaDescription: "Gold savings schemes that collect and confirm themselves — installment reminders, Razorpay reconciliation and home collection scheduling, automatic.",
        keywords: "gold savings scheme software, jewellery scheme management software, razorpay reconciliation jewellery, home collection scheme app",
        lead: "Gold savings schemes that collect and confirm themselves. Installment reminders go out ahead of due dates, and payments reconcile against the scheme ledger automatically.",
        sections: [
            {
                heading: "A reminder before a customer misses a payment, not after",
                body: "Installment reminders send automatically ahead of a scheme's due date, so a customer is nudged before they'd miss a payment rather than chased down afterward.",
            },
            {
                heading: "Collection without a counter visit",
                body: "Razorpay payments reconcile against the scheme ledger with no manual entry, and home collection pickups can be scheduled directly from the app, without a phone call to arrange them.",
            },
        ],
        bullets: [
            "Amount & weight-based schemes — standalone or tied to a future purchase.",
            "Installment reminders, automatic — sent ahead of due dates, before a customer misses one.",
            "Razorpay payments reconcile themselves — matched against the scheme ledger, no manual entry.",
            "Home collection, scheduled from the app — field agent pickup requests flow in without a phone call.",
        ],
        mockup: "schemes",
        stat: { value: "1,842", label: "active scheme enrollments tracked live in a typical deployment" },
        faqs: [
            { q: "Do customers get reminded before an installment is due?", a: "Yes, reminders send automatically ahead of the due date." },
            { q: "How are scheme payments reconciled?", a: "Razorpay payments match against the scheme ledger automatically, with no manual entry required." },
            { q: "Can a customer arrange home collection without calling the store?", a: "Yes, home collection pickup requests can be scheduled directly from the app." },
        ],
    },
    {
        slug: "repairs-tracking",
        category: "Module",
        tone: "gold",
        icon: <FiClock />,
        title: "Repairs & Tracking",
        seoTitle: "Jewellery Repair Tracking Software with Public Status Portal",
        metaTitle: "Jewellery Repairs & Tracking Software | PrepJewellery ERP",
        metaDescription: "Customers stop calling to ask 'is it ready?' — a public tracking link shows the exact same status the counter sees, no login required.",
        keywords: "jewellery repair tracking software, public repair status portal, whatsapp repair notifications jewellery",
        lead: "Customers stop calling to ask \"is it ready?\" A public tracking link shows the exact same status the counter sees — no login, and no phone call required.",
        sections: [
            {
                heading: "A status page that doesn't require an account",
                body: "The public tracking link shows a repair's live status — intake, in service, ready for pickup, picked up — without requiring the customer to log in or download anything.",
            },
            {
                heading: "WhatsApp closes the two moments that matter most",
                body: "A WhatsApp message fires automatically at intake and again the moment a repair is marked ready for pickup, covering the two points a customer is most likely to otherwise call about.",
            },
        ],
        bullets: [
            "WhatsApp sent at intake and at ready-for-pickup — the customer is notified automatically, both times.",
            "Public tracking link, no login required — the customer sees the exact same status the counter does.",
            "No staff callback needed — a repair's status is always self-serve, not dependent on someone picking up the phone.",
        ],
        mockup: "repairs",
        faqs: [
            { q: "Does the customer need an app or login to track a repair?", a: "No, the tracking link is public — no login or app install is required." },
            { q: "When does the customer get notified automatically?", a: "At intake and again when the repair is marked ready for pickup, both over WhatsApp." },
            { q: "Does staff need to call the customer to update them?", a: "No, status is always self-serve via the public link and the automatic WhatsApp messages." },
        ],
    },
    {
        slug: "accounts-finance",
        category: "Module",
        tone: "blue",
        icon: <FiCreditCard />,
        title: "Accounts & Finance",
        seoTitle: "Jewellery Accounting Software with Automated Bank Reconciliation",
        metaTitle: "Jewellery Accounts & Finance Software | PrepJewellery ERP",
        metaDescription: "Month-end becomes a review, not a reconstruction — automated bank reconciliation, TDS, gold revaluation and a full double-entry system.",
        keywords: "jewellery accounting software, double entry jewellery erp, gold revaluation accounting software, bank reconciliation jewellery",
        lead: "Month-end becomes a review, not a reconstruction. Bank lines match against vouchers automatically, so accounts spends month-end reviewing exceptions instead of rebuilding the ledger.",
        sections: [
            {
                heading: "Reconciliation that happens continuously",
                body: "Bank lines auto-match against vouchers as transactions occur, so only genuine exceptions need a human look by the time month-end review actually happens.",
            },
            {
                heading: "A real double-entry system underneath every module",
                body: "Chart of Accounts, vouchers, cashbook and ledgers sit underneath every module in the platform, with TDS and gold revaluation entries posting automatically against the day's transactions and rate.",
            },
        ],
        bullets: [
            "Bank lines auto-matched — only genuine exceptions need a human look.",
            "TDS & gold revaluation, automatic — entries post against the day's transactions and rate.",
            "Full double-entry system — Chart of Accounts, vouchers, cashbook and ledgers underneath every module.",
            "Ageing analysis refreshes continuously — not just when someone asks for it.",
        ],
        mockup: "accounts",
        faqs: [
            { q: "Is bank reconciliation a month-end task here?", a: "No, matching happens continuously — month-end becomes a review of exceptions, not a full reconstruction." },
            { q: "Is gold revaluation entered manually?", a: "No, TDS and gold revaluation entries post automatically against the day's transactions and rate." },
            { q: "Is there a real accounting system underneath, or just reports?", a: "A full double-entry system — Chart of Accounts, vouchers, cashbook and ledgers — underlies every module." },
        ],
    },
    {
        slug: "hr-payroll",
        category: "Module",
        tone: "green",
        icon: <FiUserCheck />,
        title: "HR & Payroll",
        seoTitle: "Jewellery HR & Payroll Software — Attendance to Payroll, One Flow",
        metaTitle: "Jewellery HR & Payroll Software | PrepJewellery ERP",
        metaDescription: "Attendance and incentives flow straight into payroll — no separate reconciliation step, sales-floor incentives credit automatically.",
        keywords: "jewellery hr payroll software, attendance payroll automation jewellery, incentive payroll integration software",
        lead: "Attendance and incentives flow straight into payroll. Payroll becomes a final review, not a separate reconciliation exercise, across every branch.",
        sections: [
            {
                heading: "Payroll runs on attendance that's already recorded",
                body: "Attendance drives payroll directly, with no separate reconciliation step at month-end, because the same attendance record used day to day is what payroll reads from.",
            },
            {
                heading: "Sales-floor earnings arrive already credited",
                body: "The incentive wallet from Sales & POS feeds the payroll run automatically, and leave balances auto-deduct as requests are approved — none of it waits for a year-end audit to catch up.",
            },
        ],
        bullets: [
            "Attendance drives payroll directly — no separate reconciliation step at month-end.",
            "Incentive wallet feeds the payroll run — sales-floor earnings from Sales & POS credit automatically.",
            "Leave balances auto-deduct — as requests are approved, not at year-end audit.",
        ],
        mockup: "hr",
        stat: { value: "64", label: "staff across branches shown on a single payroll run" },
        faqs: [
            { q: "Does payroll require a separate attendance reconciliation?", a: "No, attendance drives payroll directly, without a separate reconciliation step." },
            { q: "How do sales incentives reach payroll?", a: "The incentive wallet from Sales & POS feeds the payroll run automatically." },
            { q: "When do leave balances get deducted?", a: "As leave requests are approved, not at a year-end audit." },
        ],
    },

    // ---------- Also built in ----------
    {
        slug: "maxsell-gold-testing-integration",
        category: "Also Built In",
        tone: "gold",
        icon: <FiCpu />,
        title: "MaxSell Gold-Testing Integration",
        seoTitle: "MaxSell XRF Gold-Testing Hardware Integration for Jewellery ERP",
        metaTitle: "MaxSell Gold-Testing Integration | PrepJewellery ERP",
        metaDescription: "A direct hardware link to MaxSell XRF analysers — a purity reading is captured straight into the ledger, never retyped by hand.",
        keywords: "maxsell integration software, xrf gold testing hardware link, gold purity ledger integration",
        lead: "A direct hardware link to MaxSell XRF analysers — a purity reading is captured straight into the ledger, never retyped by hand.",
        sections: [
            {
                heading: "One of several places automation reaches into hardware",
                body: "PrepJewellery ERP connects directly to MaxSell's Karat Pro, Karat Prime and Aurum analysers, so a purity reading is captured straight into the Old Metal Exchange and Purchase ledger the instant the scan completes.",
            },
            {
                heading: "Tied to compliance, not just convenience",
                body: "Every reading ties permanently to its transaction, shares the same stock-release gate as HUID hallmarking capture, and any deviation from declared purity routes automatically to manager approval.",
            },
        ],
        bullets: [
            "Audit-linked — every reading ties permanently to its transaction.",
            "Hallmarking-linked — shares the same stock-release gate as HUID capture.",
            "Tolerance-gated — deviation from declared purity routes to manager approval.",
        ],
        mockup: "purchase",
        faqs: [
            { q: "Which MaxSell models are supported?", a: "Karat Pro, Karat Prime and Aurum all connect directly to the ledger." },
            { q: "Does a purity reading ever need to be typed in manually?", a: "No, it's captured straight from the machine into the Old Metal Exchange and Purchase ledger." },
            { q: "What happens if a reading doesn't match the declared purity?", a: "It routes to manager approval automatically, based on a configured tolerance." },
        ],
    },
    {
        slug: "whatsapp-automation-12-events",
        category: "Also Built In",
        tone: "gold",
        icon: <FiMessageCircle />,
        title: "WhatsApp Automation, 12 Events",
        seoTitle: "12-Event WhatsApp Business Automation for Jewellery Stores",
        metaTitle: "WhatsApp Automation Software | PrepJewellery ERP",
        metaDescription: "12 business events fire a WhatsApp message automatically — the actual PDF, receipt or invoice attached, at the moment the transaction happens.",
        keywords: "whatsapp business automation jewellery, jewellery whatsapp receipts, automated whatsapp notifications erp",
        lead: "12 business events fire a WhatsApp message automatically — the actual PDF, receipt or invoice attached, at the moment the transaction happens, not a marketing chatbot bolted on afterwards.",
        sections: [
            {
                heading: "Every one of the 12 events, live at the moment it happens",
                body: "Sales invoices, scheme enrollments, repair status changes, DC cancellation OTPs and walk-in thank-yous all fire automatically, attaching the actual document rather than a generic notification.",
            },
            {
                heading: "One delivery layer underneath all 12",
                body: "Idempotency keys prevent duplicate sends, failed messages retry automatically up to two attempts with back-off, and messaging never blocks or delays the underlying transaction it's attached to.",
            },
        ],
        bullets: [
            "Idempotency keys prevent duplicate sends.",
            "Automatic retry with back-off, up to 2 attempts.",
            "Messaging never blocks the underlying transaction.",
        ],
        mockup: null,
        stat: { value: "12", label: "business events that fire a WhatsApp message automatically" },
        faqs: [
            { q: "Does a customer ever get the same WhatsApp message twice?", a: "No, idempotency keys prevent duplicate sends even on retry." },
            { q: "What happens if a WhatsApp message fails to send?", a: "It retries automatically, up to two attempts with back-off." },
            { q: "Can a slow WhatsApp send delay a sale or a repair update?", a: "No, messaging never blocks or delays the underlying transaction." },
        ],
    },
    {
        slug: "public-repair-tracking-portal",
        category: "Also Built In",
        tone: "gold",
        icon: <FiMapPin />,
        title: "Public Repair Tracking Portal",
        seoTitle: "Public Repair Tracking Portal Software for Jewellery Stores",
        metaTitle: "Public Repair Tracking Portal | PrepJewellery ERP",
        metaDescription: "Customers check repair status on a public link — no login, no phone call to the store required.",
        keywords: "public repair tracking portal, jewellery repair status link, no login repair tracking software",
        lead: "Customers check repair status on a public link — no login, no phone call to the store required.",
        sections: [
            {
                heading: "The exact status the counter sees, made public",
                body: "The tracking portal shows the same live status the counter uses internally — intake, in service, ready for pickup, picked up — without requiring any account or app install.",
            },
            {
                heading: "Fewer calls, because the two key moments are covered",
                body: "WhatsApp pushes fire automatically at intake and at ready-for-pickup, covering the two moments a customer is most likely to otherwise pick up the phone about.",
            },
        ],
        bullets: [
            "No login required to check status.",
            "WhatsApp pushes at intake and at ready-for-pickup.",
            "Fewer \"is it ready?\" calls to the counter.",
        ],
        mockup: "repairs",
        faqs: [
            { q: "Does the customer need to create an account to use the portal?", a: "No, it's a public link — no login is required." },
            { q: "Is the tracking status delayed compared to what staff see?", a: "No, it's the exact same live status the counter sees internally." },
            { q: "Does this replace WhatsApp updates or work alongside them?", a: "Alongside — WhatsApp pushes still fire at intake and ready-for-pickup, in addition to the public link." },
        ],
    },
    {
        slug: "full-audit-trail-approval-gates",
        category: "Also Built In",
        tone: "gold",
        icon: <FiCheckSquare />,
        title: "Full Audit Trail & Approval Gates",
        seoTitle: "Full Audit Trail & Approval Gate Software for Jewellery ERP",
        metaTitle: "Jewellery Audit Trail & Approval Gates | PrepJewellery ERP",
        metaDescription: "Every automated action is logged — who, what, when — and approval gates are enforced in code, not left to a paper checklist.",
        keywords: "jewellery erp audit trail software, approval gate software jewellery, tamper evident ledger jewellery erp",
        lead: "Every automated action is logged — who, what, when — and approval gates are enforced in code, not left to a paper checklist.",
        sections: [
            {
                heading: "Automated actions are logged too, not just user edits",
                body: "A WhatsApp send, a stock-release block, a wallet credit or an OTP request are all recorded in the audit trail the same way a manual user edit is — automation doesn't create a blind spot.",
            },
            {
                heading: "Gates that can't be talked around",
                body: "Hallmarking release, purity tolerance and DC cancellation are all enforced as approval gates in code, so a step can't be skipped on a verbal sign-off the way it could be on a paper checklist.",
            },
        ],
        bullets: [
            "Every automated action logged, not just user edits.",
            "Approval gates in code, not a paper checklist.",
            "Tamper-evident record for every ledger and stock change.",
        ],
        mockup: null,
        faqs: [
            { q: "Are automated actions logged the same way as manual ones?", a: "Yes, every automated action is logged — not just actions a person directly took." },
            { q: "Can an approval gate be bypassed by a manager's verbal say-so?", a: "No, gates like hallmarking release and DC cancellation are enforced in code, not left to a paper process." },
            { q: "Is the audit record tamper-evident?", a: "Yes, every ledger and stock change is recorded in a tamper-evident audit trail." },
        ],
    },
];

export const detailsBySlug = details.reduce((acc, d) => {
    acc[d.slug] = d;
    return acc;
}, {});

export default details;
