import {
    FiClipboard, FiPercent, FiUploadCloud, FiPackage, FiPrinter, FiFileText, FiUser, FiGrid, FiHome,
    FiCreditCard, FiShoppingBag, FiTruck, FiMessageCircle, FiLayers, FiUsers, FiGlobe, FiTag, FiBarChart2,
} from "react-icons/fi";

// Each entry drives one /products/prepprint/:slug page.
//   title        — short name, shown as the "old way" (problems) or in the breadcrumb
//   seoTitle     — the actual <h1>, written around the target keyword
//   metaTitle / metaDescription / keywords — <title>/<meta> tags (see useSEO)
//   mockup       — reuses a Mockups.jsx component as the page's visual; null = text-only layout
const details = [
    // ---------- Problems ----------
    {
        slug: "orders-scribbled-paper-docket",
        category: "The Problem",
        tone: "red",
        icon: <FiClipboard />,
        title: "Orders scribbled on a paper docket",
        seoTitle: "Digital Job Docket Software for Print Shops — Replace Paper Orders",
        metaTitle: "Print Shop Job Docket Software | PrepPrint",
        metaDescription: "Specs, quantity and deadline shouldn't live on a slip of paper that can go missing. PrepPrint tracks every job in one queue from intake to dispatch.",
        keywords: "print shop job docket software, digital order tracking print shop, print job management software",
        lead: "Specs, quantity and deadline live on a slip of paper that can go missing — and a missing docket means a job nobody can find, promised to a customer nobody can call back accurately.",
        sections: [
            { heading: "Every order lands in one tracked queue", body: "Walk-in, phone and online orders all land in the same queue — New Order, Artwork Received, In Print, Finishing, Ready for Pickup — instead of a slip of paper that can be misplaced or overwritten." },
            { heading: "Nothing ships late because nobody noticed the deadline", body: "Urgent jobs surface automatically based on their due date, so a rush order doesn't quietly queue behind a job with more slack." },
        ],
        bullets: [
            "Add jobs from any channel — walk-in, phone or online, every order lands in one queue.",
            "Deadline-aware ordering — urgent jobs surface automatically, so nothing ships late.",
            "Full job history — every status change, note and file logged against the job.",
            "Export anytime — one click to CSV for offline review or accounting.",
        ],
        mockup: "orderJob",
        stat: { value: "86", label: "jobs tracked in one queue view, in a typical week" },
        faqs: [
            { q: "Can a job docket go missing the way a paper one can?", a: "No, every order lives in a tracked digital queue instead of a physical slip of paper." },
            { q: "How does staff know which job is urgent?", a: "Urgent jobs surface automatically based on their deadline, rather than depending on someone noticing." },
            { q: "Is there a record of everything that happened to a job?", a: "Yes, every status change, note and file is logged against the job in its full history." },
        ],
    },
    {
        slug: "quote-worked-out-by-hand",
        category: "The Problem",
        tone: "red",
        icon: <FiPercent />,
        title: "Every quote worked out by hand",
        seoTitle: "Automated Print Quotation Software — Instant Rate-Card Pricing",
        metaTitle: "Print Shop Quotation Software | PrepPrint",
        metaDescription: "Paper, plate and finishing costs shouldn't be recalculated on a calculator every time. PrepPrint's rate cards quote themselves instantly.",
        keywords: "print shop quotation software, print estimation software, automated print pricing calculator",
        lead: "Paper, plate and finishing costs recalculated on a calculator, every single time — a process that eats minutes on every quote and still leaves room for a typo.",
        sections: [
            { heading: "A rate card that does the math", body: "Size, quantity and finishing auto-calculate the quote the instant they're entered, replacing back-of-envelope math with a rate card configured once per material." },
            { heading: "An accepted quote becomes a job, not a re-entry", body: "Bulk and slab pricing breakpoints apply automatically for larger orders, and once a quote is accepted it converts into a live job with one tap, no re-typing." },
        ],
        bullets: [
            "Rate cards, per material — flex, vinyl, paper stock and lamination rates configured once, applied everywhere.",
            "Instant, accurate pricing — size, quantity and finishing auto-calculate the quote, no more back-of-envelope math.",
            "Bulk & slab pricing — set quantity breakpoints so larger orders price themselves correctly, automatically.",
            "One tap to convert to an order — an accepted quote becomes a live job, no re-entry, no mismatch.",
        ],
        mockup: "quote",
        stat: { value: "₹919", label: "an example flex-banner quote, calculated instantly from size and finishing" },
        faqs: [
            { q: "Does every quote need to be worked out manually?", a: "No, size, quantity and finishing auto-calculate the price instantly from the configured rate card." },
            { q: "Can larger orders get automatic bulk pricing?", a: "Yes, quantity breakpoints apply automatically so larger orders price themselves correctly." },
            { q: "Does an accepted quote need to be re-entered as a job?", a: "No, it converts into a live job with one tap." },
        ],
    },
    {
        slug: "artwork-scattered-chats-folders",
        category: "The Problem",
        tone: "red",
        icon: <FiUploadCloud />,
        title: "Artwork scattered across chats and folders",
        seoTitle: "Print Job Artwork Management Software — One File Per Job",
        metaTitle: "Print Shop Artwork Upload Software | PrepPrint",
        metaDescription: "\"Which file did the customer actually send?\" shouldn't be asked on every reprint. PrepPrint ties every artwork file to its job automatically.",
        keywords: "print shop artwork management software, design file upload print job, print job file tracking software",
        lead: "\"Which file did the customer actually send?\" — asked on every reprint or reorder, because the actual file is buried somewhere in a chat thread or a shared folder nobody indexed.",
        sections: [
            { heading: "The file stays attached to the job, automatically", body: "Customers or designers drop artwork straight onto the job — PDF, AI or high-res images — and it stays tied there without anyone having to dig through chats or folders later." },
            { heading: "Reprints don't start with a search", body: "Past artwork stays on file, ready to pull up for a repeat order in seconds, instead of re-asking the customer to resend a file from months ago." },
        ],
        bullets: [
            "Upload from anywhere — customers or designers drop artwork straight onto the job, PDF, AI or high-res images.",
            "Every file, tied to the job — artwork stays attached to its order automatically, no digging through chats or folders.",
            "Straight to the operator — the uploaded file is right there at the press, no manual transfer, no USB drives.",
            "Reprints made simple — past artwork stays on file, ready to pull up for a repeat order in seconds.",
        ],
        mockup: "artwork",
        faqs: [
            { q: "Where does a customer's artwork end up?", a: "Attached directly to its job automatically, rather than living in a chat thread or a shared folder." },
            { q: "Does the operator need the file transferred manually?", a: "No, the uploaded file is available right at the press, with no USB drive or manual handoff." },
            { q: "Is old artwork available for a reprint months later?", a: "Yes, past artwork stays on file and can be pulled up in seconds." },
        ],
    },
    {
        slug: "paper-stock-runs-out",
        category: "The Problem",
        tone: "red",
        icon: <FiPackage />,
        title: "Nobody knows the paper stock till it runs out",
        seoTitle: "Print Shop Inventory & Low-Stock Alert Software",
        metaTitle: "Print Shop Stock Management Software | PrepPrint",
        metaDescription: "A job shouldn't get halfway printed before someone notices the roll is empty. PrepPrint deducts stock automatically and alerts before it runs out.",
        keywords: "print shop inventory software, low stock alert printing business, paper stock management software",
        lead: "A job gets halfway printed before someone notices the roll is empty — and now a deadline slips while someone runs out to buy more stock.",
        sections: [
            { heading: "Stock deducts the moment a job goes to print", body: "Paper, ink and vinyl usage is deducted from stock automatically as a job goes to print, instead of being tallied later from memory or a monthly count." },
            { heading: "An alert before the roll actually runs out", body: "Reorder levels trigger a WhatsApp or app alert before stock is exhausted, so a job never gets halfway printed on an empty roll." },
        ],
        bullets: [
            "Auto-deduct on every job — paper, ink and vinyl usage is deducted from stock the moment a job goes to print.",
            "Low-stock alerts, before it's too late — reorder levels trigger a WhatsApp or app alert, never mid-print surprises.",
            "Per-branch stock visibility — owners see stock across every branch, and can transfer between them in a tap.",
            "Wastage & consumption reports — see exactly which jobs or materials are eating into margins.",
        ],
        mockup: "inventory",
        stat: { value: "42", label: "materials tracked live across a typical branch" },
        faqs: [
            { q: "Does staff need to manually deduct stock after a job?", a: "No, paper, ink and vinyl usage deducts automatically the moment a job goes to print." },
            { q: "How is staff warned about low stock?", a: "A reorder level triggers a WhatsApp or app alert before the material actually runs out." },
            { q: "Can stock be moved between branches easily?", a: "Yes, owners see stock across every branch and can transfer between them in a tap." },
        ],
    },
    {
        slug: "machines-double-booked",
        category: "The Problem",
        tone: "red",
        icon: <FiPrinter />,
        title: "Machines double-booked, deadlines missed",
        seoTitle: "Print Press Scheduling Software — Stop Double-Booking Machines",
        metaTitle: "Print Shop Press Scheduling Software | PrepPrint",
        metaDescription: "No shared view of which press is free means urgent jobs queue behind slow ones. PrepPrint gives every machine one shared, real-time schedule.",
        keywords: "print press scheduling software, printing machine booking software, print shop production schedule",
        lead: "No shared view of which press is free, so urgent jobs queue behind slow ones — and a customer's pickup time is really just a guess.",
        sections: [
            { heading: "One queue, every machine, visible live", body: "Every press's current job, operator and ETA sits on one shared schedule, so staff can see exactly what's running and what's free without walking the shop floor." },
            { heading: "A press slot confirmed before a promise is made", body: "Every job is assigned a press slot before it's confirmed to the customer, so a pickup time is based on the real queue instead of an optimistic guess." },
        ],
        bullets: [
            "One queue, every machine — see exactly what's running and what's free, live.",
            "Realistic ETAs — customers get accurate pickup times, based on the real queue.",
            "No more double-booking — every job is assigned a press slot before it's confirmed.",
            "Operator accountability — every job is tied to the operator and machine that ran it.",
        ],
        mockup: "pressSchedule",
        stat: { value: "5", label: "machines shown on one live schedule, in a typical shop" },
        faqs: [
            { q: "Can two jobs get scheduled on the same press by mistake?", a: "No, every job is assigned a press slot before it's confirmed, preventing double-booking." },
            { q: "How accurate is a customer's pickup time?", a: "It's based on the real, live press queue rather than a rough estimate." },
            { q: "Is a job's operator and machine tracked?", a: "Yes, every job is tied to the operator and machine that ran it." },
        ],
    },
    {
        slug: "gst-billing-rushed",
        category: "The Problem",
        tone: "red",
        icon: <FiFileText />,
        title: "GST billing done at the very end, in a rush",
        seoTitle: "GST-Ready Billing Software for Print Shops",
        metaTitle: "Print Shop GST Billing Software | PrepPrint",
        metaDescription: "Invoices hand-typed after the job ships are riddled with copy-paste errors. PrepPrint generates GST-ready invoices automatically at the counter.",
        keywords: "print shop gst billing software, print shop invoicing software, gst invoice generator printing business",
        lead: "Invoices hand-typed after the job ships, riddled with copy-paste errors — a rushed final step that turns a completed job into a billing headache.",
        sections: [
            { heading: "GST-ready the moment the bill is raised", body: "Every invoice generates with the correct HSN codes and tax slabs applied automatically, instead of being hand-typed and rechecked after the job has already shipped." },
            { heading: "One ledger, whatever payment method was used", body: "Split and partial payments are tracked from intake through pickup, any payment method reconciles the same day, and every counter and branch rolls into one daily sales register." },
        ],
        bullets: [
            "GST invoices, auto-generated — HSN codes and tax slabs applied correctly, every time.",
            "Split & partial payments — advance at intake, balance on pickup, tracked automatically.",
            "UPI & card, right at the counter — accept any payment method, reconciled the same day.",
            "Multi-counter, one ledger — every counter and branch rolls into one daily sales register.",
        ],
        mockup: "billing",
        stat: { value: "61%", label: "of collections made online in a typical multi-counter shop" },
        faqs: [
            { q: "Are GST invoices generated automatically?", a: "Yes, with the correct HSN codes and tax slabs applied every time, without manual entry." },
            { q: "Can a customer pay part now and part later?", a: "Yes, split and partial payments are tracked automatically from intake through pickup." },
            { q: "Do multiple counters need separate sales registers?", a: "No, every counter and branch rolls into one daily sales register." },
        ],
    },
    {
        slug: "repeat-customers-zero-history",
        category: "The Problem",
        tone: "red",
        icon: <FiUser />,
        title: "Repeat customers, zero history",
        seoTitle: "Print Shop Customer & Order History Software",
        metaTitle: "Print Shop Customer History Software | PrepPrint",
        metaDescription: "A customer's last design, size and rate shouldn't live in someone's memory. PrepPrint keeps every past order one file away.",
        keywords: "print shop customer history software, repeat customer print order tracking, print shop crm software",
        lead: "Their last design, size and rate live in someone's memory, not a record — so a repeat order depends entirely on whoever remembers that customer.",
        sections: [
            { heading: "A profile that remembers, even if staff doesn't", body: "A customer's lifetime value, preferred rate and payment history sit on one profile, so a repeat order or a reprint never starts with re-asking basic questions." },
            { heading: "Past designs, saved and ready to reuse", body: "Every artwork file stays linked to the customer, ready to reuse or revise, so a reprint of last year's design doesn't require a fresh upload." },
        ],
        bullets: [
            "Every past order, one click away — reprint last year's design at the same spec without a single question asked.",
            "Custom rates per customer — set negotiated discounts or bulk rates that apply automatically on every quote.",
            "Payment reliability, at a glance — see who pays on time before extending credit on a rush order.",
            "Past designs, saved forever — every artwork file stays linked to the customer, ready to reuse or revise.",
        ],
        mockup: "customerHistory",
        stat: { value: "₹42,600", label: "a typical repeat customer's lifetime value, visible on one profile" },
        faqs: [
            { q: "Can staff reprint a customer's past design without asking questions?", a: "Yes, every past order is one click away, at the same spec." },
            { q: "Can negotiated rates apply automatically?", a: "Yes, custom rates per customer apply automatically on every new quote." },
            { q: "How does staff know if a customer pays on time?", a: "Payment reliability is visible at a glance before extending credit on a rush order." },
        ],
    },
    {
        slug: "orders-scattered-channels",
        category: "The Problem",
        tone: "red",
        icon: <FiGrid />,
        title: "Walk-in, phone and online orders, scattered",
        seoTitle: "Unified Order Intake Software for Print Shops",
        metaTitle: "Print Shop Order Intake Software | PrepPrint",
        metaDescription: "Three intake channels, three different registers, nothing reconciled. PrepPrint puts walk-in, phone and online orders in one queue.",
        keywords: "print shop order intake software, multi channel print order management, print shop order register software",
        lead: "Three intake channels, three different registers — nothing reconciled, so a busy day means checking three separate places just to know what's actually been ordered.",
        sections: [
            { heading: "One queue, no matter how the order came in", body: "Walk-in, phone and online orders all land in the same tracked queue, so there's one place to check instead of three separate registers." },
            { heading: "A queue that already knows what's urgent", body: "Because every channel feeds the same queue, deadline-aware ordering can surface urgent jobs automatically, regardless of which channel they arrived through." },
        ],
        bullets: [
            "Add jobs from any channel — walk-in, phone or online, every order lands in one queue.",
            "Deadline-aware ordering — urgent jobs surface automatically, so nothing ships late.",
            "Full job history — every status change, note and file logged against the job.",
            "Export anytime — one click to CSV for offline review or accounting.",
        ],
        mockup: "orderJob",
        faqs: [
            { q: "Do walk-in, phone and online orders end up in different places?", a: "No, they all land in the same tracked queue regardless of channel." },
            { q: "Can staff tell which order needs attention first?", a: "Yes, urgent jobs surface automatically based on deadline, across every channel." },
            { q: "Is there one combined record of all orders?", a: "Yes, and it can be exported to CSV anytime for offline review or accounting." },
        ],
    },
    {
        slug: "owners-no-cross-branch-view",
        category: "The Problem",
        tone: "red",
        icon: <FiHome />,
        title: "Owners can't see across branches",
        seoTitle: "Multi-Branch Print Shop Management Software with Franchise Console",
        metaTitle: "Multi-Branch Print Shop Software | PrepPrint",
        metaDescription: "No consolidated view of sales, job profitability or machine utilization across branches. PrepPrint rolls every branch up into one franchise console.",
        keywords: "multi branch print shop software, franchise print shop management software, print shop owner dashboard",
        lead: "No consolidated view of sales, job profitability or machine utilization — an owner running more than one branch is left stitching updates together by phone.",
        sections: [
            { heading: "Every branch, rolled into one console", body: "A single franchise console adds branches, replicates rate cards and rolls up sales, job margin and stock reports, without a separate login or spreadsheet per branch." },
            { heading: "Patterns that surface without asking", body: "AI insights read patterns across every branch automatically — a branch with a thin margin line or strong utilization surfaces on its own, in plain English." },
        ],
        bullets: [
            "Consolidated dashboard across all branches and presses.",
            "Add branches and replicate rate cards from one console.",
            "Consolidated sales, margin and stock reports.",
            "Custom job types and tax rules per branch.",
        ],
        mockup: null,
        stat: { value: "50", label: "branches supported on one platform, without re-platforming later" },
        faqs: [
            { q: "Can an owner see sales and margin across every branch at once?", a: "Yes, a consolidated dashboard rolls up every branch and press into one view." },
            { q: "Does adding a new branch mean starting from scratch?", a: "No, rate cards and settings replicate from the franchise console instead of being configured separately per branch." },
            { q: "Can each branch still have its own job types and tax rules?", a: "Yes, those are configurable per branch." },
        ],
    },

    // ---------- Modules ----------
    {
        slug: "order-job-management",
        category: "Module",
        tone: "indigo",
        icon: <FiClipboard />,
        title: "Order & Job Management",
        seoTitle: "Print Shop Order & Job Management Software",
        metaTitle: "Print Shop Job Management Software | PrepPrint",
        metaDescription: "Every job, one queue — from intake to dispatch. Walk-in, phone and online orders tracked stage by stage, with deadline-aware ordering.",
        keywords: "print shop job management software, print order tracking software, print shop workflow software",
        lead: "Every job, one queue — from intake to dispatch. Walk-in, phone and online orders all land in the same tracked queue, so nothing ships late and nothing gets lost.",
        sections: [
            { heading: "One queue, every stage, every channel", body: "New Order, Artwork Received, In Print, Finishing and Ready for Pickup are all stages of the same queue, so a job never has to be re-entered as it moves through the shop." },
            { heading: "A full history behind every job", body: "Every status change, note and file is logged against the job, and the whole queue can be exported to CSV anytime for offline review or accounting." },
        ],
        bullets: [
            "Add jobs from any channel — walk-in, phone or online, every order lands in one queue.",
            "Deadline-aware ordering — urgent jobs surface automatically, so nothing ships late.",
            "Full job history — every status change, note and file logged against the job.",
            "Export anytime — one click to CSV for offline review or accounting.",
        ],
        mockup: "orderJob",
        stat: { value: "86", label: "jobs tracked in one queue view, in a typical week" },
        faqs: [
            { q: "Does every order channel feed the same queue?", a: "Yes, walk-in, phone and online orders all land in one tracked queue." },
            { q: "How are urgent jobs prioritized?", a: "They surface automatically based on deadline, rather than depending on someone noticing." },
            { q: "Can the job queue be exported for accounting?", a: "Yes, one click exports it to CSV anytime." },
        ],
    },
    {
        slug: "quotation-estimation",
        category: "Module",
        tone: "blue",
        icon: <FiPercent />,
        title: "Quotation & Estimation",
        seoTitle: "Automated Print Quotation & Estimation Software",
        metaTitle: "Print Shop Quotation Software | PrepPrint",
        metaDescription: "A rate card that quotes itself — instant, accurate pricing across every material, with bulk and slab pricing built in.",
        keywords: "print shop quotation software, print job estimation software, automated print pricing software",
        lead: "A rate card that quotes itself. Size, quantity and finishing auto-calculate the quote the instant they're entered — no back-of-envelope math.",
        sections: [
            { heading: "Pricing that's configured once, applied everywhere", body: "Flex, vinyl, paper stock and lamination rates are set once per material and apply automatically to every future quote, instead of being recalculated by hand each time." },
            { heading: "From accepted quote to live job, in one tap", body: "Bulk and slab pricing breakpoints price larger orders correctly on their own, and an accepted quote converts into a live job instantly, with no re-entry or mismatch." },
        ],
        bullets: [
            "Rate cards, per material — flex, vinyl, paper stock and lamination rates configured once, applied everywhere.",
            "Instant, accurate pricing — size, quantity and finishing auto-calculate the quote, no more back-of-envelope math.",
            "Bulk & slab pricing — set quantity breakpoints so larger orders price themselves correctly, automatically.",
            "One tap to convert to an order — an accepted quote becomes a live job, no re-entry, no mismatch.",
        ],
        mockup: "quote",
        stat: { value: "₹919", label: "an example flex-banner quote, calculated instantly from size and finishing" },
        faqs: [
            { q: "How is a quote's price calculated?", a: "Size, quantity and finishing auto-calculate it instantly from the configured rate card." },
            { q: "Are bulk orders priced correctly without manual work?", a: "Yes, quantity breakpoints handle bulk and slab pricing automatically." },
            { q: "What happens when a customer accepts a quote?", a: "It converts into a live job with one tap, with no re-entry." },
        ],
    },
    {
        slug: "design-artwork-upload",
        category: "Module",
        tone: "green",
        icon: <FiUploadCloud />,
        title: "Design & Artwork Upload",
        seoTitle: "Print Job Artwork & Design File Upload Software",
        metaTitle: "Print Shop Artwork Upload Software | PrepPrint",
        metaDescription: "Every file, attached to the right job. Customers or designers upload artwork straight onto the job, tied there automatically.",
        keywords: "print shop artwork upload software, design file management printing business, print job file tracking software",
        lead: "Every file, attached to the right job. Customers or designers drop artwork straight onto the job, and it stays tied there automatically.",
        sections: [
            { heading: "Uploaded once, tied to the job forever", body: "PDF, AI or high-res images upload straight onto the job from anywhere, and the file stays attached automatically — no digging through chats or folders on a reprint." },
            { heading: "From upload to the press, without a manual handoff", body: "The uploaded file is right there at the operator's press with no manual transfer or USB drive, and past artwork stays on file for repeat orders." },
        ],
        bullets: [
            "Upload from anywhere — customers or designers drop artwork straight onto the job, PDF, AI or high-res images.",
            "Every file, tied to the job — artwork stays attached to its order automatically, no digging through chats or folders.",
            "Straight to the operator — the uploaded file is right there at the press, no manual transfer, no USB drives.",
            "Reprints made simple — past artwork stays on file, ready to pull up for a repeat order in seconds.",
        ],
        mockup: "artwork",
        faqs: [
            { q: "Where can artwork be uploaded from?", a: "From anywhere — customers or designers can drop PDF, AI or high-res files straight onto the job." },
            { q: "Does the file need to be manually handed to the operator?", a: "No, it's available right at the press without a USB drive or manual transfer." },
            { q: "Is a customer's old artwork available for a reprint?", a: "Yes, it stays on file and can be pulled up in seconds." },
        ],
    },
    {
        slug: "pos-gst-billing",
        category: "Module",
        tone: "green",
        icon: <FiCreditCard />,
        title: "POS & GST Billing",
        seoTitle: "Print Shop POS & GST Billing Software",
        metaTitle: "Print Shop POS & GST Billing | PrepPrint",
        metaDescription: "Counter billing that's already GST-ready — auto-generated invoices, split payments and a single ledger across every counter.",
        keywords: "print shop pos software, gst billing software printing business, print shop counter billing software",
        lead: "Counter billing that's already GST-ready. Every invoice generates with the correct HSN codes and tax slabs applied automatically.",
        sections: [
            { heading: "GST correctness without a manual double-check", body: "HSN codes and tax slabs apply correctly on every invoice automatically, so billing doesn't need a manual review after the job has already shipped." },
            { heading: "Every counter, one ledger", body: "Split and partial payments are tracked from intake through pickup, any payment method reconciles the same day, and every counter and branch rolls into one daily sales register." },
        ],
        bullets: [
            "GST invoices, auto-generated — HSN codes and tax slabs applied correctly, every time.",
            "Split & partial payments — advance at intake, balance on pickup, tracked automatically.",
            "UPI & card, right at the counter — accept any payment method, reconciled the same day.",
            "Multi-counter, one ledger — every counter and branch rolls into one daily sales register.",
        ],
        mockup: "billing",
        stat: { value: "61%", label: "of collections made online in a typical multi-counter shop" },
        faqs: [
            { q: "Are GST invoices correct without manual review?", a: "Yes, HSN codes and tax slabs apply correctly automatically on every invoice." },
            { q: "Can a customer pay an advance and settle the balance later?", a: "Yes, split and partial payments are tracked automatically from intake through pickup." },
            { q: "Do multiple counters share one sales ledger?", a: "Yes, every counter and branch rolls into one daily sales register." },
        ],
    },
    {
        slug: "inventory-stock",
        category: "Module",
        tone: "red",
        icon: <FiPackage />,
        title: "Inventory & Stock",
        seoTitle: "Print Shop Inventory & Low-Stock Alert Software",
        metaTitle: "Print Shop Inventory Software | PrepPrint",
        metaDescription: "Never find out the stock is empty mid-job — paper, ink and vinyl auto-deduct on every job, with low-stock alerts before it's too late.",
        keywords: "print shop inventory software, paper stock tracking software, low stock alert printing business",
        lead: "Never find out the stock is empty mid-job. Paper, ink and vinyl usage is deducted from stock the moment a job goes to print.",
        sections: [
            { heading: "Stock that updates itself as jobs run", body: "Paper, ink and vinyl usage deducts from stock automatically the moment a job goes to print, so the stock count never needs a manual recount to stay accurate." },
            { heading: "A warning before the roll actually runs dry", body: "Reorder levels trigger a WhatsApp or app alert before stock is exhausted, and owners can see and transfer stock across every branch in a tap." },
        ],
        bullets: [
            "Auto-deduct on every job — paper, ink and vinyl usage is deducted from stock the moment a job goes to print.",
            "Low-stock alerts, before it's too late — reorder levels trigger a WhatsApp or app alert, never mid-print surprises.",
            "Per-branch stock visibility — owners see stock across every branch, and can transfer between them in a tap.",
            "Wastage & consumption reports — see exactly which jobs or materials are eating into margins.",
        ],
        mockup: "inventory",
        stat: { value: "42", label: "materials tracked live across a typical branch" },
        faqs: [
            { q: "Does stock need to be manually deducted after every job?", a: "No, paper, ink and vinyl usage deducts automatically the moment a job goes to print." },
            { q: "How early is a low-stock warning sent?", a: "Before the material actually runs out, triggered by a configured reorder level." },
            { q: "Can stock be transferred between branches?", a: "Yes, in a tap, once owners see stock levels across every branch." },
        ],
    },
    {
        slug: "machine-press-scheduling",
        category: "Module",
        tone: "indigo",
        icon: <FiPrinter />,
        title: "Machine & Press Scheduling",
        seoTitle: "Print Press Machine Scheduling Software",
        metaTitle: "Print Shop Press Scheduling Software | PrepPrint",
        metaDescription: "Every press, one shared schedule — see exactly what's running and what's free, with realistic ETAs and no more double-booking.",
        keywords: "print press scheduling software, printing machine booking software, print shop production planning",
        lead: "Every press, one shared schedule. Every machine's current job, operator and ETA is visible on one queue, live.",
        sections: [
            { heading: "What's running, what's free — visible at a glance", body: "The full press queue — machine, current job, operator and ETA — is visible in one place, replacing a walk around the shop floor or a phone call to check." },
            { heading: "A slot confirmed before a promise is made", body: "Every job gets a press slot assigned before its pickup time is confirmed to the customer, so urgent jobs never end up queued behind a slower one by accident." },
        ],
        bullets: [
            "One queue, every machine — see exactly what's running and what's free, live.",
            "Realistic ETAs — customers get accurate pickup times, based on the real queue.",
            "No more double-booking — every job is assigned a press slot before it's confirmed.",
            "Operator accountability — every job is tied to the operator and machine that ran it.",
        ],
        mockup: "pressSchedule",
        stat: { value: "5", label: "machines shown on one live schedule, in a typical shop" },
        faqs: [
            { q: "Can staff see which press is free without walking the floor?", a: "Yes, the full press queue is visible live in one place." },
            { q: "Are customer pickup times accurate?", a: "Yes, they're based on the real press queue, not a rough estimate." },
            { q: "Is every job tied to a specific operator and machine?", a: "Yes, for accountability on every job." },
        ],
    },
    {
        slug: "customer-order-history",
        category: "Module",
        tone: "blue",
        icon: <FiUser />,
        title: "Customer & Order History",
        seoTitle: "Print Shop Customer & Order History Software",
        metaTitle: "Print Shop Customer History Software | PrepPrint",
        metaDescription: "Every repeat customer, one file away — lifetime value, preferred rate and payment history on one profile, with past designs saved forever.",
        keywords: "print shop customer history software, repeat customer tracking print shop, print shop crm software",
        lead: "Every repeat customer, one file away. Lifetime value, preferred rate and payment history sit on one profile, ready for the next order.",
        sections: [
            { heading: "A profile, not a memory, behind every repeat order", body: "A customer's lifetime value, preferred rate and payment history are all visible on one profile, so a repeat order or reprint never starts with re-asking basic questions." },
            { heading: "Designs and rates that don't need to be rebuilt", body: "Custom rates apply automatically on every quote for that customer, and every artwork file stays linked to them, ready to reuse or revise." },
        ],
        bullets: [
            "Every past order, one click away — reprint last year's design at the same spec without a single question asked.",
            "Custom rates per customer — set negotiated discounts or bulk rates that apply automatically on every quote.",
            "Payment reliability, at a glance — see who pays on time before extending credit on a rush order.",
            "Past designs, saved forever — every artwork file stays linked to the customer, ready to reuse or revise.",
        ],
        mockup: "customerHistory",
        stat: { value: "₹42,600", label: "a typical repeat customer's lifetime value, visible on one profile" },
        faqs: [
            { q: "Can a customer's past order be reprinted without asking questions?", a: "Yes, every past order is one click away, at the same spec." },
            { q: "Do negotiated rates need to be re-applied on every quote?", a: "No, custom rates per customer apply automatically." },
            { q: "How does staff decide whether to extend credit?", a: "Payment reliability is visible at a glance on the customer's profile." },
        ],
    },
    {
        slug: "vendor-purchase",
        category: "Module",
        tone: "purple",
        icon: <FiShoppingBag />,
        title: "Vendor & Purchase",
        seoTitle: "Print Shop Vendor & Purchase Management Software",
        metaTitle: "Print Shop Purchase Management Software | PrepPrint",
        metaDescription: "Raw material buying, off the notebook — purchase orders raised straight from low stock, with supplier ledgers always current.",
        keywords: "print shop purchase management software, vendor ledger printing business, raw material po software",
        lead: "Raw material buying, off the notebook. A low-stock alert can become a purchase order in one tap, with every supplier ledger current automatically.",
        sections: [
            { heading: "A reorder alert that can become a PO instantly", body: "When stock crosses its reorder level, that same alert can become a purchase order in one tap, instead of a separate manual step to contact the supplier." },
            { heading: "Supplier ledgers and job costs, always current", body: "What's owed to every vendor stays current automatically without a separate register, and purchase cost feeds straight into true job profitability rather than a rough estimate." },
        ],
        bullets: [
            "POs raised straight from low stock — a reorder alert can become a purchase order in one tap.",
            "Supplier ledgers, always current — track what's owed to every vendor without a separate register.",
            "Delivery tracking, per PO — know what's ordered, in transit or delivered, at a glance.",
            "Cost-of-goods, tied to jobs — purchase cost feeds straight into true job profitability.",
        ],
        mockup: "vendorPurchase",
        faqs: [
            { q: "Does a low-stock alert require a separate purchase order step?", a: "No, the alert can become a purchase order in one tap." },
            { q: "Is there a separate register to track what's owed to vendors?", a: "No, supplier ledgers stay current automatically on the same platform." },
            { q: "Does purchase cost affect job profitability calculations?", a: "Yes, purchase cost feeds straight into true job profitability." },
        ],
    },
    {
        slug: "delivery-dispatch",
        category: "Module",
        tone: "green",
        icon: <FiTruck />,
        title: "Delivery & Dispatch",
        seoTitle: "Print Shop Delivery & Dispatch Tracking Software",
        metaTitle: "Print Shop Delivery & Dispatch Software | PrepPrint",
        metaDescription: "From press to doorstep, tracked all the way — pickup or delivery, courier sync, proof-of-delivery and automatic ready-for-pickup alerts.",
        keywords: "print shop delivery tracking software, print job dispatch software, courier tracking printing business",
        lead: "From press to doorstep, tracked all the way. Customers pick a fulfillment option at order time, and every step after is tracked automatically.",
        sections: [
            { heading: "Fulfillment chosen once, tracked automatically", body: "Customers pick walk-in, courier or home delivery at order time, and the shipment hands off to a courier partner and gets tracked without leaving PrepPrint." },
            { heading: "Proof and notifications, without a phone call", body: "Signature or photo confirmation attaches to the job automatically on delivery, and a WhatsApp ping fires the moment a job clears finishing and is ready for pickup." },
        ],
        bullets: [
            "Pickup or delivery, your choice — customers pick a fulfillment option at order time: walk-in, courier or home delivery.",
            "Courier & logistics partner sync — hand off to your courier partner and track the shipment without leaving PrepPrint.",
            "Proof-of-delivery on file — signature or photo confirmation attached to the job automatically.",
            "Ready-for-pickup alerts — customers get a WhatsApp ping the moment their job clears finishing.",
        ],
        mockup: "dispatch",
        faqs: [
            { q: "Can a customer choose how they'll receive their order?", a: "Yes, walk-in, courier or home delivery, chosen at order time." },
            { q: "Does dispatch tracking require leaving PrepPrint for a courier's own app?", a: "No, shipments track directly within PrepPrint once handed off to the courier partner." },
            { q: "Is there proof once a delivery is completed?", a: "Yes, a signature or photo confirmation attaches to the job automatically." },
        ],
    },
    {
        slug: "whatsapp-order-updates",
        category: "Module",
        tone: "indigo",
        icon: <FiMessageCircle />,
        title: "WhatsApp Order Updates",
        seoTitle: "Automated WhatsApp Order Update Software for Print Shops",
        metaTitle: "Print Shop WhatsApp Order Updates | PrepPrint",
        metaDescription: "Every update, every order — straight to WhatsApp. Order confirmations, artwork-received alerts, ready-for-pickup pings and payment links, automatic.",
        keywords: "print shop whatsapp automation, automated order confirmation printing business, whatsapp ready for pickup alert software",
        lead: "Every update, every order — straight to WhatsApp. Order confirmations, artwork-received alerts and ready-for-pickup pings go out automatically, so the counter stops fielding \"is my order ready?\" calls.",
        sections: [
            { heading: "Every milestone, confirmed automatically", body: "A new order gets an automatic WhatsApp confirmation with the estimate, and artwork uploads get their own confirmation the moment the file is attached to the job." },
            { heading: "The two calls that stop coming in", body: "Ready-for-pickup and delivery alerts, plus payment links and receipts sent the moment they're generated, cover the two moments a customer is most likely to otherwise call about." },
        ],
        bullets: [
            "Order confirmations, instantly — every new order gets an automatic WhatsApp confirmation with the estimate.",
            "Artwork received, confirmed instantly — customers get a WhatsApp confirmation the moment their file is uploaded and attached to the job.",
            "Ready-for-pickup & delivery alerts — no more \"is my order ready?\" calls to the counter.",
            "Payment links & receipts — balance dues and paid receipts, sent the moment they're generated.",
        ],
        mockup: "whatsappOrder",
        faqs: [
            { q: "Does a customer get notified when their order is confirmed?", a: "Yes, automatically, with the estimate attached." },
            { q: "How does a customer know their artwork was received?", a: "A WhatsApp confirmation fires the moment the file is uploaded and attached to the job." },
            { q: "Does staff need to call customers when a job is ready?", a: "No, a WhatsApp alert fires automatically for ready-for-pickup and delivery." },
        ],
    },

    // ---------- Also built in ----------
    {
        slug: "rate-card-bulk-pricing-rules",
        category: "Also Built In",
        tone: "indigo",
        icon: <FiPercent />,
        title: "Rate Card & Bulk Pricing Rules",
        seoTitle: "Rate Card & Bulk Pricing Rules Software for Print Shops",
        metaTitle: "Print Shop Rate Card Software | PrepPrint",
        metaDescription: "Rate cards per material with quantity breakpoints, so bulk orders price themselves correctly without a manual recalculation.",
        keywords: "print shop rate card software, bulk pricing rules printing business, print job pricing automation",
        lead: "Rate cards per material with quantity breakpoints, so bulk orders price themselves correctly without a manual recalculation.",
        sections: [
            { heading: "One rate card, applied to every quote", body: "Rates for flex, vinyl, paper stock and lamination are configured once and applied automatically to every future quote for that material." },
            { heading: "Bulk pricing that doesn't need a lookup table", body: "Quantity breakpoints handle bulk and slab pricing automatically, so a larger order prices itself correctly without anyone checking a printed rate sheet." },
        ],
        bullets: [
            "Rates configured once, applied to every quote.",
            "Bulk & slab pricing breakpoints, automatic.",
            "No back-of-envelope math at the counter.",
        ],
        mockup: "quote",
        faqs: [
            { q: "Does every quote need its rate re-entered?", a: "No, rates are configured once per material and applied automatically to every quote." },
            { q: "How does bulk pricing get applied?", a: "Automatically, via quantity breakpoints configured on the rate card." },
            { q: "Is a printed rate sheet still needed at the counter?", a: "No, the rate card handles the pricing directly." },
        ],
    },
    {
        slug: "multi-branch-franchise-management",
        category: "Also Built In",
        tone: "indigo",
        icon: <FiLayers />,
        title: "Multi-Branch & Franchise Management",
        seoTitle: "Multi-Branch & Franchise Print Shop Management Console",
        metaTitle: "Multi-Branch Print Shop Management | PrepPrint",
        metaDescription: "One franchise console rolls up every branch's rate cards, staff and reports — add branches and replicate settings without starting from scratch.",
        keywords: "multi branch print shop software, franchise print shop console, print shop owner reporting software",
        lead: "One franchise console rolls up every branch — rate cards, staff and reports, replicated or reviewed from a single dashboard.",
        sections: [
            { heading: "Adding a branch doesn't mean starting over", body: "Rate cards and settings replicate from the franchise console, so a new branch doesn't need to be configured from a blank slate." },
            { heading: "Reports that roll up automatically", body: "Sales, margin and stock reports consolidate across every branch, giving an owner one place to check instead of separate branch logins." },
        ],
        bullets: [
            "Add branches and replicate rate cards from one console.",
            "Consolidated sales, margin and stock reports.",
            "Custom job types and tax rules per branch.",
        ],
        mockup: null,
        faqs: [
            { q: "Does every branch need separate rate card setup?", a: "No, rate cards replicate from a single franchise console." },
            { q: "Can an owner see all branches' performance in one view?", a: "Yes, sales, margin and stock reports consolidate across every branch." },
            { q: "Can job types and tax rules differ by branch?", a: "Yes, those are configurable per branch." },
        ],
    },
    {
        slug: "staff-operator-management",
        category: "Also Built In",
        tone: "indigo",
        icon: <FiUsers />,
        title: "Staff & Operator Management",
        seoTitle: "Print Shop Staff & Operator Management Software",
        metaTitle: "Print Shop Staff Management Software | PrepPrint",
        metaDescription: "Operators see only their press queue; managers and counter staff see only their own branch — role-scoped access from day one.",
        keywords: "print shop staff management software, operator management printing business, print shop role based access",
        lead: "Operators see only their press queue; managers and counter staff see only their own branch — role-scoped from day one.",
        sections: [
            { heading: "Every role sees only what it needs", body: "An operator's view is scoped to their own press queue, and counter staff see only their own branch, instead of everyone seeing the full company database." },
            { heading: "Accountability built into every job", body: "Every job is tied to the operator and machine that ran it, so accountability doesn't depend on anyone remembering who worked on what." },
        ],
        bullets: [
            "Role-based access for every staff type.",
            "Operator accountability tied to every job.",
            "Attendance and shift visibility per branch.",
        ],
        mockup: null,
        faqs: [
            { q: "Can an operator see jobs from another press?", a: "No, an operator's view is scoped to their own press queue." },
            { q: "Can counter staff see other branches?", a: "No, they see only their own branch." },
            { q: "Is a job tied to the operator who ran it?", a: "Yes, for accountability on every job." },
        ],
    },
    {
        slug: "online-ordering-portal",
        category: "Also Built In",
        tone: "indigo",
        icon: <FiGlobe />,
        title: "Online Ordering Portal",
        seoTitle: "Online Ordering Portal Software for Print Shops",
        metaTitle: "Print Shop Online Ordering Portal | PrepPrint",
        metaDescription: "A branded ordering portal lets customers upload artwork, get an instant quote and track their job — without a phone call.",
        keywords: "print shop online ordering software, print job customer portal, online print order tracking",
        lead: "A branded ordering portal lets customers upload artwork, get an instant quote and track their job — without a phone call.",
        sections: [
            { heading: "Ordering that doesn't need a phone call", body: "Customers upload artwork and get an instant quote directly through the portal, instead of calling the counter to describe what they need." },
            { heading: "The same job status, visible to the customer", body: "Job status stays visible to the customer live, through the same portal used to place the order, so \"is it ready?\" calls drop off." },
        ],
        bullets: [
            "Customers quote and order without calling the counter.",
            "Artwork upload built into the same portal.",
            "Job status visible to the customer, live.",
        ],
        mockup: null,
        faqs: [
            { q: "Does a customer need to call the shop to place an order?", a: "No, they can upload artwork and get an instant quote through the portal." },
            { q: "Is artwork upload part of the ordering flow?", a: "Yes, it's built into the same portal, not a separate step." },
            { q: "Can a customer track their job status themselves?", a: "Yes, live, through the same portal." },
        ],
    },
    {
        slug: "barcode-job-ticket-tracking",
        category: "Also Built In",
        tone: "indigo",
        icon: <FiTag />,
        title: "Barcode & Job-Ticket Tracking",
        seoTitle: "Barcode Job-Ticket Tracking Software for Print Shops",
        metaTitle: "Print Shop Barcode Tracking Software | PrepPrint",
        metaDescription: "Every job prints its own barcode ticket, so scanning a job at any stage pulls up its full status instantly.",
        keywords: "print shop barcode tracking software, job ticket scanning printing business, print job tracking barcode",
        lead: "Every job prints its own barcode ticket, so scanning a job at any stage pulls up its full status instantly.",
        sections: [
            { heading: "A ticket generated the moment a job is created", body: "Every job gets a scannable barcode ticket on intake, rather than a handwritten label that can be copied incorrectly." },
            { heading: "Status updates by scan, not by memory", body: "Scanning a job's ticket at any stage pulls up its full status and lets staff update it directly, reducing mix-ups between similar-looking jobs." },
        ],
        bullets: [
            "Every job gets a scannable ticket on intake.",
            "Scan to update stage, no manual lookup.",
            "Reduces mix-ups between similar jobs.",
        ],
        mockup: null,
        faqs: [
            { q: "When is a job's barcode ticket generated?", a: "On intake, automatically, for every job." },
            { q: "Does updating a job's stage require a manual lookup?", a: "No, scanning the ticket pulls up its status directly." },
            { q: "Does this help with similar-looking jobs?", a: "Yes, scanning reduces mix-ups between jobs that otherwise look alike." },
        ],
    },
    {
        slug: "reports-ai-insights",
        category: "Also Built In",
        tone: "purple",
        icon: <FiBarChart2 />,
        title: "Reports & AI Insights",
        seoTitle: "AI-Powered Reports for Print Shop Margins & Utilization",
        metaTitle: "Print Shop AI Reports Software | PrepPrint",
        metaDescription: "PrepPrint reads the patterns across jobs, machines and stock, and tells owners what actually needs attention, in plain English.",
        keywords: "print shop reporting software, ai insights printing business, print shop margin analysis software",
        lead: "PrepPrint reads the patterns across jobs, machines and stock, and tells owners what actually needs attention, in plain English.",
        sections: [
            { heading: "Insights, not just raw numbers", body: "Instead of a dashboard full of numbers to interpret, PrepPrint surfaces margin, utilization and payment insights automatically, in plain English." },
            { heading: "Comparisons across branches, without a spreadsheet", body: "Branch-to-branch comparisons and flagged issues surface on their own, so an owner catches a problem before it grows instead of finding it in a month-end spreadsheet." },
        ],
        bullets: [
            "Margin, utilization and payment insights, automatic.",
            "Branch-to-branch comparison, without a spreadsheet.",
            "Flagged issues before they become a bigger problem.",
        ],
        mockup: null,
        stat: { value: "34%", label: "a typical average job margin, tracked as a rolling 30-day figure" },
        faqs: [
            { q: "Does an owner need to build reports manually?", a: "No, margin, utilization and payment insights surface automatically." },
            { q: "Can branches be compared without a spreadsheet?", a: "Yes, branch-to-branch comparison is built in." },
            { q: "Are issues flagged before they become serious?", a: "Yes, that's the point of the automated insights — catching a problem early." },
        ],
    },
];

export const detailsBySlug = details.reduce((acc, d) => {
    acc[d.slug] = d;
    return acc;
}, {});

export default details;
