import {
    FiClock, FiFileText, FiMonitor, FiEyeOff, FiBarChart2, FiUsers, FiActivity, FiGrid,
    FiCamera, FiCalendar, FiCheckSquare, FiBriefcase, FiSun, FiRefreshCw, FiSmartphone,
    FiShield, FiUserCheck, FiUser, FiGlobe, FiLock,
} from "react-icons/fi";

// Each entry drives one /products/prepdesk/:slug page.
//   title        — short name, shown as the "old way" (problems) or in the breadcrumb
//   seoTitle     — the actual <h1>, written around the target keyword
//   metaTitle / metaDescription / keywords — <title>/<meta> tags (see useSEO)
//   mockup       — reuses a Mockups.jsx component as the page's visual; null = text-only layout
const details = [
    // ---------- Problems ----------
    {
        slug: "day-went-nowhere",
        category: "The Problem",
        tone: "red",
        icon: <FiClock />,
        title: "Nobody knows where the day went",
        seoTitle: "Automatic Time Tracking Software — Know Where Every Hour Went",
        metaTitle: "Automatic Time Tracking Software | PrepDesk",
        metaDescription: "Stop reconciling timesheets against guesswork. PrepDesk tracks time automatically, offline-first, with idle detection built in — no manual entry.",
        keywords: "automatic time tracking software, employee time tracking app, time tracking without manual entry",
        lead: "Hours logged on a timesheet rarely match hours actually worked. Without automatic tracking, every payroll cycle starts with a reconciliation nobody enjoys and nobody fully trusts.",
        sections: [
            {
                heading: "The timer runs itself",
                body: "A lightweight desktop widget starts and stops the day with one click — no browser tab to keep open, no end-of-day guess at what time someone actually logged in.",
            },
            {
                heading: "Idle time doesn't quietly become billable time",
                body: "The timer auto-pauses after a period of inactivity and prompts before counting that time as work, so a lunch break or a step away from the desk doesn't inflate the day's total.",
            },
        ],
        bullets: [
            "One-click clock in/out from a lightweight desktop widget — no browser tab, no manual entry.",
            "Runs quietly in the background, tracking time against the active project as people switch tasks.",
            "Idle detection auto-pauses the timer after inactivity and prompts before counting it as work.",
            "Offline-first — keeps tracking with no internet and syncs the moment connectivity returns.",
        ],
        mockup: "timeTracker",
        stat: { value: "<1%", label: "CPU footprint per agent" },
        faqs: [
            { q: "Does PrepDesk track time automatically, or does someone have to start a timer manually?", a: "Both are supported — a one-click widget starts and stops the day, and time tracks automatically against whichever project or task is active." },
            { q: "What happens if a laptop loses internet connection mid-day?", a: "Tracking continues offline and syncs automatically the moment connectivity returns — nothing is lost." },
            { q: "Does idle time get counted as work automatically?", a: "No — the timer pauses after a period of inactivity and prompts the user before counting any of that idle time as work." },
        ],
    },
    {
        slug: "attendance-excel",
        category: "The Problem",
        tone: "red",
        icon: <FiFileText />,
        title: "Attendance still runs on Excel",
        seoTitle: "Attendance & Shift Management Software — Replace the Excel Register",
        metaTitle: "Attendance Management Software | PrepDesk",
        metaDescription: "Replace manual attendance registers with automated rosters, real-time late/absent flags and location-aware holiday calendars.",
        keywords: "attendance management software, shift roster software, employee attendance app",
        lead: "Manual registers, cross-checked shifts and disputed leave balances every month — an Excel sheet doesn't reconcile itself against who actually clocked in.",
        sections: [
            {
                heading: "The roster and the clock-in agree automatically",
                body: "Recurring shifts are built per team or location, and every clock-in is matched against that roster in real time — late and absent flags appear the moment they happen, not at month-end.",
            },
            {
                heading: "Holidays and leave don't need a separate spreadsheet",
                body: "Location-aware public holiday calendars and one-tap leave requests keep attendance, holidays and time-off reconciled in the same calendar instead of three different files.",
            },
        ],
        bullets: [
            "Recurring shifts per team or location reconcile against attendance automatically.",
            "Late and absent flags appear in real time — no end-of-month reconciliation.",
            "Different offices get their own public holiday calendar, handled automatically.",
            "Leave requests, approvals and balances update instantly — no email threads.",
        ],
        mockup: "attendance",
        faqs: [
            { q: "Can PrepDesk handle different shift patterns for different teams?", a: "Yes — recurring shifts are built per team or location, and attendance reconciles against whichever roster applies." },
            { q: "How are late clock-ins detected?", a: "Clock-ins are matched against the assigned shift in real time, so a late arrival is flagged immediately rather than discovered during a manual review." },
            { q: "Does PrepDesk support multiple office locations with different holidays?", a: "Yes, holiday calendars are location-aware, so each office observes its own public holidays automatically." },
        ],
    },
    {
        slug: "one-tracker-half-team",
        category: "The Problem",
        tone: "red",
        icon: <FiMonitor />,
        title: "One tracker, half the team",
        seoTitle: "Cross-Platform Employee Monitoring Software — Windows, Mac & Linux",
        metaTitle: "Cross-Platform Time Tracking Software | PrepDesk",
        metaDescription: "Native agents for Windows, Mac and Linux with full feature parity — no OS is the \"lesser\" build, no team member stays invisible.",
        keywords: "cross platform employee monitoring, mac time tracking software, linux employee monitoring software",
        lead: "Windows gets tracked, Mac and Linux users stay completely invisible. A tool built for one operating system leaves the rest of a hybrid team out of every report.",
        sections: [
            {
                heading: "One codebase, no lesser build",
                body: "PrepDesk ships native agents for Windows, macOS and Linux from the same codebase, so feature parity isn't an afterthought — every team member shows up in the same dashboard, regardless of what they run.",
            },
            {
                heading: "Deployed the way IT actually deploys software",
                body: "Silent MSI/EXE installers for Windows, notarized MDM-deployable .dmg for Mac, and .deb/.rpm/AppImage builds for Linux mean rollout fits into existing device-management workflows instead of requiring a new one.",
            },
        ],
        bullets: [
            "Native builds for Windows 10/11, macOS 12+ (Apple Silicon & Intel) and major Linux distributions.",
            "Same feature set on every OS — no platform is the \"lesser\" build.",
            "Central deployment via GPO, SCCM, Jamf, Kandji or scriptable install for DevOps fleets.",
            "Auto-updates silently, fleet-wide, without interrupting the person working.",
        ],
        mockup: null,
        stat: { value: "3", label: "operating systems, one platform" },
        faqs: [
            { q: "Does the Mac agent run natively on Apple Silicon, or does it need Rosetta?", a: "It's a native Apple Silicon build — no Rosetta overhead — alongside a separate Intel build." },
            { q: "Can IT push the agent to hundreds of machines at once?", a: "Yes — Windows deploys via GPO or SCCM, Mac via Jamf or Kandji, and Linux via a scriptable install suited to engineering and DevOps fleets." },
            { q: "Do Linux users get the same features as Windows and Mac users?", a: "Yes, all three platforms share the same feature set from one codebase — no compromises for any OS." },
        ],
    },
    {
        slug: "monitoring-feels-surveillance",
        category: "The Problem",
        tone: "red",
        icon: <FiEyeOff />,
        title: "Monitoring feels like surveillance",
        seoTitle: "Employee Monitoring Software That Isn't a Keylogger",
        metaTitle: "Transparent Employee Monitoring Software | PrepDesk",
        metaDescription: "No keystroke logging, blur-by-default screenshots and full employee-visible dashboards — monitoring built for trust, not surveillance.",
        keywords: "employee monitoring without keylogging, transparent employee monitoring software, ethical employee tracking software",
        lead: "Bolted-on tools capture everything and explain nothing — and when employees can't see what's being recorded about them, trust breaks down fast.",
        sections: [
            {
                heading: "Activity levels, never keystrokes",
                body: "PrepDesk measures keyboard and mouse activity intensity to gauge engagement — it never records what was actually typed, which is the line that separates monitoring from surveillance.",
            },
            {
                heading: "Nothing an employee can't see about themselves",
                body: "Every team member has a dashboard showing exactly what was tracked about their own day — screenshots, apps, time — so monitoring is something that happens with them, not to them.",
            },
        ],
        bullets: [
            "No keystroke logging — PrepDesk measures activity intensity, never what was typed.",
            "Privacy blur is on by default for screenshots, with capture visible to the employee it belongs to.",
            "Monitoring depth is configurable per team or role — engineering isn't tracked the same way as field sales.",
            "Every team member can see exactly what was captured about their own day, any time.",
        ],
        mockup: null,
        faqs: [
            { q: "Does PrepDesk log what employees type?", a: "No — it measures keyboard and mouse activity intensity to gauge engagement, but never records actual keystrokes." },
            { q: "Can employees see their own tracked data?", a: "Yes, every employee has full visibility into their own tracked time, apps and screenshots — there's no black box." },
            { q: "Can monitoring depth differ between teams?", a: "Yes, screenshot frequency, app tracking and reporting granularity are all configurable per team or role." },
        ],
    },
    {
        slug: "reports-nobody-reads",
        category: "The Problem",
        tone: "red",
        icon: <FiBarChart2 />,
        title: "Reports nobody reads",
        seoTitle: "AI-Generated Workforce Reports Managers Actually Read",
        metaTitle: "AI Workforce Reporting Software | PrepDesk",
        metaDescription: "Plain-English, auto-generated digests that flag what actually needs attention — not another raw activity log dumped on a manager's desk.",
        keywords: "ai workforce reporting software, automated employee reports, plain english productivity reports",
        lead: "Raw activity logs dumped on managers, with no narrative and no next action, tend to get skimmed once and ignored after that.",
        sections: [
            {
                heading: "A written summary, not a spreadsheet to interpret",
                body: "Instead of a dashboard someone has to decode, AI Insights & Reporting turns the same underlying data into a plain-English digest — what improved, what slipped, what needs a look.",
            },
            {
                heading: "Anomalies are flagged, not buried",
                body: "A team's productivity dropping, a project's burn rate outpacing its budget, a cluster of after-hours logins — these get called out automatically instead of waiting for someone to notice them in a chart.",
            },
        ],
        bullets: [
            "Auto-generated, plain-English digests instead of raw activity dumps.",
            "Anomaly detection flags what actually needs attention — a slipping team, an over-budget project.",
            "Delivered on a daily or weekly cadence, on email or Slack.",
            "Sits on top of the same live data as the Dashboard — nothing to reconcile separately.",
        ],
        mockup: "dashboard",
        faqs: [
            { q: "How is this different from just looking at the Dashboard?", a: "The Dashboard shows live numbers; AI Insights turns the same data into a written narrative that calls out what specifically needs attention, so nobody has to interpret a chart to find the story." },
            { q: "Can digests be delivered somewhere other than email?", a: "Yes, daily or weekly digests can be routed to Slack as well as email." },
            { q: "Does it only flag problems, or good performance too?", a: "Both — it surfaces risks like productivity drops or burnout signals, and also calls out consistently strong performance worth recognizing." },
        ],
    },
    {
        slug: "payroll-disputes",
        category: "The Problem",
        tone: "red",
        icon: <FiUsers />,
        title: "Payroll built on disputes",
        seoTitle: "Payroll-Ready Time & Attendance Exports — End Overtime Disputes",
        metaTitle: "Payroll-Ready Attendance Software | PrepDesk",
        metaDescription: "Native payroll-ready exports built on the same live attendance and time data — no miscounted hours, no overtime arguments every cycle.",
        keywords: "payroll ready time tracking, overtime dispute software, attendance export payroll software",
        lead: "Miscounted hours and overtime arguments, every single cycle — when payroll is built off a spreadsheet someone re-typed from a register, disputes are baked in from the start.",
        sections: [
            {
                heading: "One source of truth, from clock-in to export",
                body: "Attendance, shifts and logged hours all live in the same system a payroll export pulls from, so there's no second copy of the data that can quietly drift out of sync with the first.",
            },
            {
                heading: "Exports built for payroll, not adapted for it",
                body: "Payroll-ready exports and native QuickBooks/Tally integration mean hours flow straight into the tool that actually runs payroll, instead of being re-keyed from a report.",
            },
        ],
        bullets: [
            "Attendance, shifts and hours all come from the same live system a payroll export pulls from.",
            "Native payroll-ready exports — no re-typing hours from a separate report.",
            "QuickBooks / Tally payroll integration available on request.",
            "Late, absent and overtime are all auto-flagged against the roster, not argued about after the fact.",
        ],
        mockup: null,
        stat: { value: "0", label: "manual re-entry between attendance and payroll" },
        faqs: [
            { q: "Does PrepDesk integrate directly with payroll software?", a: "Yes, native payroll-ready exports are built in, with QuickBooks and Tally payroll integration available on request." },
            { q: "How are overtime hours calculated?", a: "Overtime is calculated against the same roster and shift data used for attendance, so there's one number everyone is working from, not a separate manual tally." },
            { q: "Can HR export attendance for a custom pay period?", a: "Yes, exports support custom date ranges to match whatever pay cycle the business runs on." },
        ],
    },
    {
        slug: "burnout-spotted-late",
        category: "The Problem",
        tone: "red",
        icon: <FiActivity />,
        title: "Burnout, spotted too late",
        seoTitle: "AI Burnout Detection Software for Hybrid & Remote Teams",
        metaTitle: "Employee Burnout Detection Software | PrepDesk",
        metaDescription: "PrepDesk flags after-hours logins, falling engagement and unusual patterns automatically — an early signal, not a post-mortem.",
        keywords: "employee burnout detection software, after hours work tracking, remote team wellbeing monitoring",
        lead: "No early signal for overwork, after-hours logins or falling engagement means burnout is usually only visible in hindsight — after someone's already handed in notice or missed a deadline.",
        sections: [
            {
                heading: "Patterns get flagged, not just logged",
                body: "AI Insights watches for the signals that actually precede burnout — repeated after-hours activity, a sustained drop in productivity — and surfaces them as a flagged pattern, not a fact buried in a chart.",
            },
            {
                heading: "A prompt to check in, not a verdict",
                body: "A flagged employee isn't scored or penalized — the system surfaces the pattern to a manager as a cue for a human conversation, which is the point where burnout actually gets addressed.",
            },
        ],
        bullets: [
            "After-hours logins on multiple days are flagged automatically as a possible burnout risk.",
            "A sustained productivity drop for a person or team surfaces as a named insight, not a buried data point.",
            "Digests are written in plain English, framed as a prompt for a manager check-in.",
            "Sits on the same live activity data as the Dashboard — no separate wellbeing survey required.",
        ],
        mockup: "dashboard",
        faqs: [
            { q: "How does PrepDesk detect a possible burnout risk?", a: "It watches for patterns like repeated after-hours activity across multiple days or a sustained drop in productivity, and flags them automatically for a manager to review." },
            { q: "Does flagging an employee affect their productivity score?", a: "No — a flag is a prompt for a human check-in, not a penalty or a scoring mechanism." },
            { q: "Can this replace a formal employee wellbeing survey?", a: "It's a complementary early signal based on activity patterns, not a replacement for direct conversations or formal wellbeing programs." },
        ],
    },
    {
        slug: "five-subscriptions-zero-sync",
        category: "The Problem",
        tone: "red",
        icon: <FiGrid />,
        title: "Five subscriptions, zero sync",
        seoTitle: "All-in-One Workforce Platform — Replace Five Separate Tools",
        metaTitle: "All-in-One Employee Monitoring & HRMS Platform | PrepDesk",
        metaDescription: "Time tracker, attendance app, screenshot tool and leave system, replaced by one platform — one vendor, one bill, one team accountable.",
        keywords: "all in one workforce management software, replace multiple hr tools, unified employee monitoring platform",
        lead: "Time tracker, attendance app, screenshot tool and leave system — none talk to each other, so someone ends up manually reconciling five different exports every month.",
        sections: [
            {
                heading: "One platform, not five subscriptions stitched together",
                body: "Time tracking, attendance, screenshots, leave, projects and AI reporting all live in the same system by default, with nothing to connect via Zapier and nothing that can silently fall out of sync.",
            },
            {
                heading: "One vendor accountable for all of it",
                body: "When something needs fixing or customizing, there's one team that built, hosts and supports the whole platform — not five different support queues to escalate through.",
            },
        ],
        bullets: [
            "Time tracking, attendance, screenshots, leave, projects and reporting in one platform.",
            "No API limits, sync failures or Zapier glue to babysit between tools.",
            "One bill, one renewal, one support relationship instead of five.",
            "Your data stays in one place — never scattered across five vendors' servers.",
        ],
        mockup: null,
        faqs: [
            { q: "What tools does PrepDesk typically replace?", a: "Common replacements include a separate time tracker (DeskTime/Time Doctor), an activity monitor (Hubstaff/ActivTrak), a project tracker (Toggl), an HRMS (BambooHR/Deputy) and Zapier glue connecting them." },
            { q: "Does consolidating onto one platform mean losing features from the specialized tools?", a: "No — each module is built to match or exceed the equivalent standalone tool, since it's purpose-built for exactly this workflow rather than adapted from a generic base." },
            { q: "Who do we contact if something breaks?", a: "One team — Prepseed builds, hosts and supports the whole platform, so there's no finger-pointing between vendors." },
        ],
    },

    // ---------- Modules with a spotlight section on the main overview page ----------
    {
        slug: "dashboard",
        category: "Module",
        tone: "blue",
        icon: <FiGrid />,
        title: "Dashboard",
        seoTitle: "Real-Time Workforce Dashboard Software — See Every Team Member",
        metaTitle: "Workforce Dashboard Software | PrepDesk",
        metaDescription: "See your entire workforce in one glance — live productivity scoring, idle/late alerts and role-aware visibility, refreshed continuously.",
        keywords: "workforce dashboard software, employee productivity dashboard, real time team monitoring dashboard",
        lead: "Who's online, idle or offline, and a real-time productivity score — refreshed continuously, not compiled at the end of the day. One dashboard shows exactly how the team's day is going.",
        sections: [
            {
                heading: "Built-in scoring, no setup required",
                body: "Every app and site is auto-classified so a productivity percentage appears out of the box — nobody has to manually tag hundreds of tools before the numbers mean anything.",
            },
            {
                heading: "Role-aware by design",
                body: "Owners see the whole company; team leads see exactly their own reportees — the same dashboard, scoped differently depending on who's logged in.",
            },
        ],
        bullets: [
            "Who's online, idle or offline, and a real-time productivity score — refreshed continuously.",
            "Every app and site is auto-classified so a productivity percentage appears without setup.",
            "Idle time, late clock-ins and unusual patterns surface the moment they happen.",
            "Owners see the whole company; team leads see exactly their own reportees.",
        ],
        mockup: "dashboard",
        faqs: [
            { q: "Do I need to manually categorize apps before the dashboard shows useful numbers?", a: "No — a growing library auto-classifies common apps and sites as productive, unproductive or neutral out of the box." },
            { q: "How current is the data on the dashboard?", a: "It refreshes continuously — online/idle status, hours and productivity are live, not compiled at the end of the day." },
            { q: "Do team leads see the whole company's data?", a: "No, they see exactly their own reportees; only owners and admins see the full company view." },
        ],
    },
    {
        slug: "time-tracking",
        category: "Module",
        tone: "blue",
        icon: <FiClock />,
        title: "Automatic Time Tracking",
        seoTitle: "Automatic Time Tracking Software With Offline Support",
        metaTitle: "Automatic Time Tracking Software | PrepDesk",
        metaDescription: "One click to start, zero effort after that — automatic time tracking with built-in idle detection and offline-first syncing.",
        keywords: "automatic time tracking app, offline time tracking software, one click time tracker",
        lead: "One click to start. Zero effort after that. A lightweight desktop widget starts and stops the day — no browser tab, no manual entry.",
        sections: [
            {
                heading: "Tracks the active project, not just the clock",
                body: "As people switch between tasks, the timer follows the active project automatically in the background, so time-to-project mapping happens without anyone stopping to log it manually.",
            },
            {
                heading: "Never loses time to a bad connection",
                body: "The offline-first design keeps tracking with no internet — useful for field work or unreliable connections — and syncs the moment connectivity returns, with nothing lost in between.",
            },
        ],
        bullets: [
            "One-click clock in/out from a lightweight desktop widget — no browser tab, no manual entry.",
            "Runs quietly in the background, tracking time against the active project as people switch tasks.",
            "Idle detection auto-pauses the timer after inactivity and prompts before counting it as work.",
            "Offline-first — keeps tracking with no internet and syncs the moment connectivity returns.",
        ],
        mockup: "timeTracker",
        faqs: [
            { q: "Does the timer need a browser tab open to keep tracking?", a: "No — it's a native desktop widget, so there's no browser tab to keep open or accidentally close." },
            { q: "What happens during an idle period, like a lunch break?", a: "The timer auto-pauses after inactivity and prompts the user before that idle time counts as tracked work." },
            { q: "Does time tracking work without an internet connection?", a: "Yes, tracking is offline-first — it keeps working with no connectivity and syncs automatically once the connection returns." },
        ],
    },
    {
        slug: "app-web-usage",
        category: "Module",
        tone: "blue",
        icon: <FiMonitor />,
        title: "App & Website Usage",
        seoTitle: "App & Website Usage Tracking Software — Productive vs. Unproductive",
        metaTitle: "App & Website Usage Tracking Software | PrepDesk",
        metaDescription: "Every hour, auto-sorted into productive, neutral or unproductive — with team-defined categories and per-project breakdowns.",
        keywords: "app usage tracking software, website usage monitoring employee, productivity categorization software",
        lead: "Every hour, sorted into productive and not. A growing auto-categorized library tags common apps and sites out of the box, and any tag can be re-mapped to how your business actually works.",
        sections: [
            {
                heading: "Categories that match your business, not a generic default",
                body: "Figma is productive at a design studio; it might be neutral elsewhere. Any app or domain can be re-tagged by the team, so the productive/unproductive split reflects how this specific business actually works.",
            },
            {
                heading: "Per-project, not just per-person",
                body: "Usage breaks down by project as well as by person, showing which tools a project actually leans on — useful for understanding where a team's time and tools are really going.",
            },
        ],
        bullets: [
            "A growing database tags common apps and sites as productive, unproductive or neutral out of the box.",
            "Re-tag any app or domain to match your business — Figma is productive here, YouTube might not be.",
            "Per-project breakdown shows which tools each project actually leans on, not just total hours logged.",
            "Employees can pause tracking for personal breaks — nothing is captured while paused.",
        ],
        mockup: "appUsage",
        faqs: [
            { q: "Can we change how an app or website is categorized?", a: "Yes — any app or domain can be re-tagged as productive, neutral or unproductive to match how the business actually works." },
            { q: "Does usage tracking continue during a personal break?", a: "No — employees can pause tracking for personal time, and nothing is captured while paused." },
            { q: "Can I see which apps a specific project relies on most?", a: "Yes, usage breaks down per project as well as per person." },
        ],
    },
    {
        slug: "screenshots",
        category: "Module",
        tone: "blue",
        icon: <FiCamera />,
        title: "Screenshots & Activity",
        seoTitle: "Configurable Screenshot Monitoring Software — Never a Keylogger",
        metaTitle: "Employee Screenshot Monitoring Software | PrepDesk",
        metaDescription: "Configurable capture, privacy blur by default and activity-intensity tracking instead of keystrokes — visible to the employee it belongs to.",
        keywords: "employee screenshot monitoring software, screen capture productivity tool, activity monitoring without keylogger",
        lead: "Visibility with context — never a keylogger. Configurable screenshot capture paired with activity-intensity measurement, never a record of what was typed.",
        sections: [
            {
                heading: "Configurable, not all-or-nothing",
                body: "Screenshot frequency can be set per role or team — from every few minutes down to fully off — so the level of visibility matches the sensitivity and nature of the work, not a single company-wide setting.",
            },
            {
                heading: "Blur by default, transparent by design",
                body: "Sensitive content can be blurred automatically while activity context is preserved, and every employee can see exactly what was captured about their own day, closing the trust gap that bolted-on monitoring tools create.",
            },
        ],
        bullets: [
            "Set screenshot frequency per role or team — from every few minutes to fully off.",
            "Privacy blur is on by default; sensitive content can be blurred while activity context is preserved.",
            "PrepDesk measures keyboard & mouse activity intensity — it never records what was typed.",
            "Every team member can see exactly what was captured about their own day, any time.",
        ],
        mockup: "screenshots",
        faqs: [
            { q: "Can screenshot capture be turned off for certain roles?", a: "Yes, capture frequency is configurable per role or team, from every few minutes down to fully off." },
            { q: "Is blur applied automatically?", a: "Yes, privacy blur is on by default, and can be toggled depending on the organization's policy." },
            { q: "Can an employee see their own captured screenshots?", a: "Yes — every team member has full visibility into exactly what was captured about their own day." },
        ],
    },
    {
        slug: "attendance-shifts",
        category: "Module",
        tone: "blue",
        icon: <FiCalendar />,
        title: "Attendance, Shifts & Leave",
        seoTitle: "Attendance & Shift Scheduling Software — Rosters, Holidays, Leave",
        metaTitle: "Attendance & Shift Management Software | PrepDesk",
        metaDescription: "Rosters, holidays and time-off in one calendar — recurring shifts, location-aware holidays and real-time late/absent flags.",
        keywords: "shift scheduling software, attendance management software, employee leave management system",
        lead: "Rosters, holidays and time-off — one calendar. Recurring shifts, location-aware holiday calendars and instant late/absent flags, all reconciled automatically.",
        sections: [
            {
                heading: "The roster does the reconciling",
                body: "Shifts are built per team or location, and every clock-in is matched against the roster in real time — late and absent flags appear the moment they happen, with no end-of-month spreadsheet review.",
            },
            {
                heading: "Leave and holidays live in the same calendar",
                body: "Employees apply for leave in one tap, managers approve, and balances update instantly — and because holiday calendars are location-aware, different offices automatically observe their own public holidays.",
            },
        ],
        bullets: [
            "Build recurring shifts per team or location, and let attendance reconcile against them automatically.",
            "Employees apply, managers approve, balances update instantly — no email threads.",
            "Different offices, different public holidays — handled per location automatically.",
            "Clock-ins are matched to the roster in real time — late and absent flags appear instantly.",
        ],
        mockup: "attendance",
        stat: { value: "96.4%", label: "typical on-time attendance rate" },
        faqs: [
            { q: "Can different teams have different shift patterns?", a: "Yes, recurring shifts are built per team or location, and attendance reconciles against whichever roster applies to that person." },
            { q: "How quickly are late arrivals flagged?", a: "In real time — a clock-in is matched against the roster immediately, so a late flag appears right away, not at a month-end review." },
            { q: "Do leave balances update automatically after approval?", a: "Yes, balances update instantly the moment a manager approves a leave request." },
        ],
    },
    {
        slug: "leave-management",
        category: "Module",
        tone: "blue",
        icon: <FiCheckSquare />,
        title: "Leave Management",
        seoTitle: "Employee Leave Management Software — Requests & Approvals in One Tap",
        metaTitle: "Leave Management Software | PrepDesk",
        metaDescription: "Requests, approvals and balances in one tap — no email threads, with leave approvals syncing both ways with Google Calendar.",
        keywords: "leave management software, employee leave request app, leave approval workflow software",
        lead: "Requests, approvals, balances in one tap. Leave management that lives in the same system as attendance, instead of a separate form and a separate spreadsheet tracking balances.",
        sections: [
            {
                heading: "No email thread required",
                body: "An employee applies for leave, a manager approves it, and the balance updates instantly — the whole exchange happens inside PrepDesk instead of a chain of emails and a manually updated tracker.",
            },
            {
                heading: "Calendars that already know about the meeting",
                body: "Leave approvals sync both ways with Google Calendar, so an approved day off actually blocks out the calendar instead of only existing inside the leave tracker.",
            },
        ],
        bullets: [
            "Employees apply, managers approve, balances update instantly — no email threads.",
            "Location-aware holiday calendars mean different offices see their own public holidays automatically.",
            "Leave approvals sync both ways with Google Calendar.",
            "Balances, history and pending requests are visible to the employee at any time — no black box.",
        ],
        mockup: "attendance",
        faqs: [
            { q: "Do leave balances update the moment a request is approved?", a: "Yes, instantly — there's no delay or separate manual update to a spreadsheet." },
            { q: "Does an approved leave request block out the employee's calendar?", a: "Yes, leave approvals sync both ways with Google Calendar." },
            { q: "Can an employee see their own leave history and balance at any time?", a: "Yes, that visibility is always available to the employee — nothing requires asking HR." },
        ],
    },
    {
        slug: "projects-tasks",
        category: "Module",
        tone: "blue",
        icon: <FiBriefcase />,
        title: "Projects & Task Tracking",
        seoTitle: "Project Time Tracking Software — Budget vs. Actual, Billable Hours",
        metaTitle: "Project & Task Time Tracking Software | PrepDesk",
        metaDescription: "Time, tied to the work and the budget — every tracked hour maps to a project and task, with budget-vs-actual burn visible before the invoice does.",
        keywords: "project time tracking software, billable hours tracking app, budget vs actual project software",
        lead: "Time, tied to the work — and the budget. Every tracked hour lands on the right project and task, with burn-rate visibility long before an over-budget project becomes a surprise.",
        sections: [
            {
                heading: "Every hour already knows where it belongs",
                body: "Time tracks against whichever project and task is active, so there's no separate step of manually allocating hours after the fact — the mapping happens as the work happens.",
            },
            {
                heading: "Burn rate, visible before the invoice",
                body: "Budget vs. actual is tracked per project in real time, so a project running over budget shows up as a live burn percentage instead of being discovered when the final numbers are tallied.",
            },
        ],
        bullets: [
            "Every tracked hour lands on the right project & task automatically.",
            "Spot burn-rate problems before the invoice does, with budget vs. actual on every project.",
            "Separate client-billable hours from internal work with one tag.",
            "Client-ready or payroll-ready timesheets, exported in one click.",
        ],
        mockup: "projects",
        stat: { value: "102%", label: "burn flagged automatically on an over-budget project" },
        faqs: [
            { q: "Does time need to be manually assigned to a project afterward?", a: "No — time tracks against the active project and task automatically as the work happens." },
            { q: "How do I know if a project is going over budget?", a: "Budget vs. actual burn is visible in real time on every project, so an overrun shows up as it's happening rather than at invoicing." },
            { q: "Can I separate billable client hours from internal work?", a: "Yes, hours can be tagged as billable or internal with one click, keeping the two cleanly separated in reports." },
        ],
    },
    {
        slug: "ai-insights-reporting",
        category: "Module",
        tone: "blue",
        icon: <FiSun />,
        title: "AI Insights & Reporting",
        seoTitle: "AI-Powered Workforce Insights — Plain-English Anomaly Detection",
        metaTitle: "AI Workforce Insights Software | PrepDesk",
        metaDescription: "Data that explains itself in plain English — a rolling productivity index, anomaly detection and narrative digests, not just charts.",
        keywords: "ai workforce insights software, anomaly detection employee productivity, automated hr reporting software",
        lead: "Data that explains itself, in plain English. PrepDesk doesn't just log activity — it reads the patterns and tells managers what actually needs attention, before it becomes a problem.",
        sections: [
            {
                heading: "A rolling index, not just today's snapshot",
                body: "The Company Productivity Index is a rolling 7-day average weighted across all active teams, giving a stable read on team health rather than a single noisy day.",
            },
            {
                heading: "Named insights, not a wall of numbers",
                body: "A team's productivity dropping alongside a rise in meeting time, a project drifting past its budget pace, employees showing after-hours patterns — each becomes a specific, plain-English callout rather than a data point buried in a report.",
            },
        ],
        bullets: [
            "Rolling 7-day Company Productivity Index, weighted across every active team.",
            "Anomalies are named and explained — a productivity drop, a burn-rate overrun, a burnout risk pattern.",
            "Recognizes consistent high performers, not just problems.",
            "Delivered as a plain-English digest — no chart-reading required.",
        ],
        mockup: "dashboard",
        faqs: [
            { q: "What is the Company Productivity Index based on?", a: "It's a rolling 7-day average of productivity, weighted across every active team, giving a stable trend line rather than a single day's noise." },
            { q: "Does AI Insights only flag problems?", a: "No, it also surfaces consistently strong performance — like a team holding an 82% average with zero late clock-ins for six straight weeks — worth recognizing." },
            { q: "How is a burnout risk pattern identified?", a: "Repeated after-hours activity across multiple days for the same person is flagged automatically as a possible risk, prompting a manager check-in." },
        ],
    },
    {
        slug: "integrations",
        category: "Module",
        tone: "blue",
        icon: <FiRefreshCw />,
        title: "Integrations",
        seoTitle: "Workforce Platform Integrations — Slack, Google, Jira & Payroll",
        metaTitle: "PrepDesk Integrations Software | PrepDesk",
        metaDescription: "Native Slack, Google Workspace and Jira/Asana/Trello sync, plus payroll-ready exports — set up in a day, no developer required.",
        keywords: "workforce software integrations, slack time tracking integration, jira time tracking sync",
        lead: "Fits into the stack you already use. Native connections to the tools teams run their work on — no manual exports, no re-typing timesheets.",
        sections: [
            {
                heading: "Notifications where the team already is",
                body: "Slack gets clock-in reminders, leave approvals and end-of-day productivity summaries; Google Calendar meetings are auto-excluded from idle detection, with leave approvals syncing both ways.",
            },
            {
                heading: "No double entry for engineering or ops",
                body: "Time tracked in PrepDesk maps directly to the Jira, Asana or Trello ticket it was spent on, so there's no separate manual step of logging the same hours twice.",
            },
        ],
        bullets: [
            "Slack: clock-in reminders, leave approvals and productivity summaries as a daily digest.",
            "Google Workspace: calendar sync excludes meetings from idle detection; leave syncs both ways.",
            "Jira / Asana / Trello: tracked time maps directly to the ticket it was spent on.",
            "More on request: Zoom & Google Meet, GitHub/GitLab, QuickBooks/Tally payroll, Microsoft Teams, Zapier/Webhooks, SSO/SAML/Okta.",
        ],
        mockup: null,
        stat: { value: "1 day", label: "typical integration setup time" },
        faqs: [
            { q: "Do I need a developer to connect Slack, Google or Jira?", a: "No — connecting accounts takes a few clicks and is typically set up in a day, with no developer required." },
            { q: "Does a calendar meeting get flagged as idle time?", a: "No, Google Calendar meetings are automatically excluded from idle detection." },
            { q: "Is SSO supported for larger organizations?", a: "Yes, SSO/SAML/Okta integration is available on request." },
        ],
    },
    {
        slug: "cross-platform-apps",
        category: "Module",
        tone: "blue",
        icon: <FiSmartphone />,
        title: "Cross-Platform Apps",
        seoTitle: "Native Windows, Mac & Linux Time Tracking Agents",
        metaTitle: "Cross-Platform Time Tracking Agents | PrepDesk",
        metaDescription: "Native builds for Windows, macOS and Linux — not a browser plugin — with feature parity, central deployment and silent auto-updates.",
        keywords: "native time tracking agent, windows mac linux monitoring software, cross platform employee monitoring app",
        lead: "Native builds — Windows, Mac & Linux. Whatever your team runs, PrepDesk runs on it, with the same features, accuracy and lightweight footprint everywhere.",
        sections: [
            {
                heading: "A real agent, not a browser tab",
                body: "Each platform gets a proper native background service — a silent MSI/EXE on Windows, a notarized MDM-deployable .dmg on Mac, and .deb/.rpm/AppImage builds on Linux — rather than a browser extension that stops tracking the moment the tab closes.",
            },
            {
                heading: "Deployed like real fleet software",
                body: "Central deployment via GPO/SCCM, Jamf/Kandji or a scriptable install means IT can push to 500 machines the same way they'd push to 5, with auto-updates rolling out silently afterward.",
            },
        ],
        bullets: [
            "Windows 10/11 (x64/ARM64), macOS 12+ (Apple Silicon & Intel) and major Linux distributions.",
            "<1% CPU footprint — runs quietly without slowing anyone down.",
            "Central deployment: GPO/SCCM, Jamf/Kandji, or a scriptable install for DevOps fleets.",
            "Auto-updates silently, fleet-wide, with full feature parity across every OS.",
        ],
        mockup: null,
        faqs: [
            { q: "Is this a browser extension or a real desktop app?", a: "A real native background service on each platform — not a browser plugin — so tracking doesn't stop when a browser tab closes." },
            { q: "How much system resource does the agent use?", a: "Under 1% CPU footprint, designed to run quietly without slowing down the machine it's on." },
            { q: "Do updates require any action from the employee?", a: "No, updates roll out silently and automatically fleet-wide." },
        ],
    },

    // ---------- Also built in (no on-page section of their own) ----------
    {
        slug: "web-app",
        category: "Also built in",
        tone: "blue",
        icon: <FiGlobe />,
        title: "Web App",
        seoTitle: "Browser-Based Workforce Management — No Install for Managers or HR",
        metaTitle: "PrepDesk Web App | PrepDesk",
        metaDescription: "Manage everything from the browser — dashboards, reports and approvals. Only the lightweight desktop tracker installs, for time capture only.",
        keywords: "browser based workforce management software, hr web app no install, employee management dashboard software",
        lead: "Manage everything from the browser. Only the tracker installs. Dashboards, reports and approvals need nothing for HR or managers to install.",
        sections: [
            {
                heading: "One install, not one per role",
                body: "The only thing that installs on anyone's machine is the lightweight desktop tracker used for time capture — every dashboard, report and approval workflow for HR, managers and owners runs in the browser.",
            },
            {
                heading: "Published under your own domain",
                body: "The web app is published at a domain like hr.yourbrand.prepdesk.com, mirroring exactly what the desktop tracker logs in real time — PrepDesk stays invisible to anyone using it.",
            },
        ],
        bullets: [
            "Dashboards, reports & approvals — nothing for HR or managers to install.",
            "Published under your own domain — PrepDesk stays invisible.",
            "Role-based dashboards: Owner, HR, Team Lead and Employee views, one web app.",
            "Real-time sync — mirrors exactly what the desktop tracker logs, live.",
        ],
        mockup: null,
        faqs: [
            { q: "Do managers need to install anything to view reports?", a: "No — managers, HR and owners use the browser-based web app; only the lightweight desktop tracker installs, and only for time capture." },
            { q: "Can the web app be published on our own domain?", a: "Yes, it's published under your own domain, so employees never see \"Prepseed\" anywhere." },
            { q: "How current is the data shown in the web app?", a: "It's real-time — the web app mirrors exactly what the desktop tracker logs, live." },
        ],
    },
    {
        slug: "reports-analytics",
        category: "Also built in",
        tone: "blue",
        icon: <FiBarChart2 />,
        title: "Reports & Analytics",
        seoTitle: "Workforce Reports & Analytics Software — Custom Ranges, One-Click Export",
        metaTitle: "Workforce Reports & Analytics Software | PrepDesk",
        metaDescription: "Numbers that show exactly where time and cost go — custom date ranges, one-click branded export and scheduled digests.",
        keywords: "workforce analytics software, hr reports export software, employee productivity reporting tool",
        lead: "Numbers that show exactly where time and cost go. Reports built for custom date ranges, any team, any location, with a drill-down from a headline number to the exact timesheet.",
        sections: [
            {
                heading: "Every number drills down to the source",
                body: "A department-wide productivity percentage is a starting point, not the whole story — every report can be drilled into down to the exact employee and timesheet behind it.",
            },
            {
                heading: "Exports built for sharing, not just viewing",
                body: "One-click CSV and branded PDF export mean reports are as easy to send to a client or leadership as they are to review internally, and scheduled digests keep stakeholders current without anyone needing to log in.",
            },
        ],
        bullets: [
            "Custom date ranges, any period, any team, any location.",
            "One-click export — CSV & PDF, branded with your logo.",
            "Scheduled daily or weekly digests, delivered on email.",
            "Drill down from a headline number all the way to the exact timesheet.",
        ],
        mockup: null,
        stat: { value: "15,240", label: "hours summarized in a typical 30-day report" },
        faqs: [
            { q: "Can reports be filtered by team or location?", a: "Yes, custom date ranges combine with team and location filters for any period you need." },
            { q: "Can exported reports carry our own branding?", a: "Yes, one-click CSV and PDF exports are branded with your logo." },
            { q: "Can I drill from a summary number into individual timesheets?", a: "Yes, every headline number can be drilled down to the exact timesheet behind it." },
        ],
    },
    {
        slug: "privacy-compliance",
        category: "Also built in",
        tone: "blue",
        icon: <FiLock />,
        title: "Privacy & Compliance",
        seoTitle: "Employee Monitoring Privacy & Compliance Controls",
        metaTitle: "Privacy & Compliance Controls for Employee Monitoring | PrepDesk",
        metaDescription: "No keystroke logging, configurable monitoring depth, full audit trail and data residency options — transparent by default, on both sides.",
        keywords: "employee monitoring privacy compliance, data residency employee monitoring software, audit trail hr software",
        lead: "Transparent by default. Every employee can see exactly what's tracked about them, and every organization controls exactly how deep that tracking goes.",
        sections: [
            {
                heading: "Compliance controls, not just a promise",
                body: "Data residency options let you choose where data is stored to meet regional requirements, and a full audit trail logs every access to an employee's data — visibility that cuts both ways, not just top-down.",
            },
            {
                heading: "Configurable depth, not one policy for everyone",
                body: "Monitoring depth — screenshots, app tracking, reporting granularity — is configurable by team, role or location, so engineering and field sales aren't held to the same monitoring policy by default.",
            },
        ],
        bullets: [
            "No keystroke logging — activity intensity is measured, never what was typed.",
            "Screenshots blur by default, with capture visible to the employee it belongs to.",
            "Data residency options let you choose where your data is stored, for regional compliance.",
            "A full audit trail logs every access to an employee's data.",
        ],
        mockup: null,
        faqs: [
            { q: "Can we choose where our data is physically stored?", a: "Yes, data residency options are available to meet regional compliance requirements." },
            { q: "Is there a log of who accessed an employee's monitoring data?", a: "Yes, a full audit trail records every access, so visibility applies to the monitoring system itself, not just the employees being monitored." },
            { q: "Can monitoring policy differ by role?", a: "Yes, screenshot frequency, app tracking and reporting depth are all configurable per team, role or location." },
        ],
    },

    // ---------- Roles ----------
    {
        slug: "owner-admin",
        category: "Team Role",
        tone: "green",
        icon: <FiShield />,
        title: "Owner / Admin",
        seoTitle: "PrepDesk for Owners — Full Company Visibility & Control",
        metaTitle: "Workforce Platform for Business Owners & Admins | PrepDesk",
        metaDescription: "Full visibility across every team, location and report — plus control over roles, billing and every integration.",
        keywords: "workforce management software for owners, hrms admin access control, company wide productivity dashboard",
        lead: "Full visibility across every team, location and report. Controls roles, billing & integrations — the one role that sees the whole company.",
        sections: [
            {
                heading: "The complete company picture",
                body: "Every team, every location and every report is visible to the Owner/Admin in real time — the only role with unrestricted access to the full, unscoped dataset.",
            },
            {
                heading: "Control over the platform itself",
                body: "Roles, permissions, billing and every third-party integration are managed from the same account, so the owner decides exactly how tightly or loosely access is set for everyone else.",
            },
        ],
        bullets: [
            "Full visibility across every team, location and report, in real time.",
            "Controls user roles, permissions, billing and every integration.",
            "The only role with access to the complete, unscoped company database.",
            "Sets monitoring policy — screenshot frequency, tracking depth — per team or role.",
        ],
        mockup: "dashboard",
        faqs: [
            { q: "Is Owner/Admin the only role that sees the whole company?", a: "Yes — every other role is scoped to their own team or data by default; only Owner/Admin sees the complete, unscoped view." },
            { q: "Can an owner set different monitoring rules for different teams?", a: "Yes, monitoring depth — screenshots, app tracking, reporting granularity — is configurable per team or role from the Owner/Admin account." },
            { q: "Who manages billing and integrations?", a: "The Owner/Admin account controls billing and every third-party integration." },
        ],
    },
    {
        slug: "hr-manager",
        category: "Team Role",
        tone: "green",
        icon: <FiUserCheck />,
        title: "HR Manager",
        seoTitle: "HR Manager Dashboard — Attendance, Leave & Payroll Exports",
        metaTitle: "HR Manager Software for Attendance & Payroll | PrepDesk",
        metaDescription: "Attendance, leave approvals, shift rosters and payroll exports, company-wide — without owner-level access to every setting.",
        keywords: "hr manager software, attendance leave approval software, payroll export hr tool",
        lead: "Attendance, leave approvals, shift rosters and payroll exports company-wide — the operational view an HR team actually needs, without full platform control.",
        sections: [
            {
                heading: "Company-wide, on the workflows HR owns",
                body: "Attendance, leave approvals and shift rosters are visible and manageable company-wide for the HR Manager role, covering exactly the workflows HR is responsible for.",
            },
            {
                heading: "Payroll exports without a manual reconciliation step",
                body: "Payroll-ready exports pull straight from the same attendance and time data HR already manages, so there's no separate spreadsheet to reconcile before payroll runs.",
            },
        ],
        bullets: [
            "Company-wide visibility into attendance, leave approvals and shift rosters.",
            "Payroll-ready exports pulled directly from live attendance and time data.",
            "Approves or rejects leave requests with balances updating instantly.",
            "Doesn't require Owner/Admin-level access to billing or integrations.",
        ],
        mockup: "attendance",
        faqs: [
            { q: "Does the HR Manager role see every team's attendance company-wide?", a: "Yes, attendance, leave and shift rosters are visible company-wide for this role." },
            { q: "Can an HR Manager export payroll-ready hours directly?", a: "Yes, payroll-ready exports are available to this role, pulled from the same live attendance and time data." },
            { q: "Does HR Manager access include billing and integrations?", a: "No, those remain scoped to Owner/Admin; HR Manager access is focused on attendance, leave and payroll exports." },
        ],
    },
    {
        slug: "team-lead",
        category: "Team Role",
        tone: "green",
        icon: <FiCheckSquare />,
        title: "Team Lead",
        seoTitle: "Team Lead Dashboard — Productivity Trends for Your Own Team",
        metaTitle: "Team Lead Productivity Dashboard Software | PrepDesk",
        metaDescription: "Dashboards, productivity trends and task assignment for a team lead's own team only — not the whole company.",
        keywords: "team lead productivity dashboard, manager team monitoring software, task assignment software for managers",
        lead: "Dashboards, productivity trends and task assignment for their own team only — a manager's view scoped to exactly the people they lead.",
        sections: [
            {
                heading: "Scoped to the team that reports to them",
                body: "A Team Lead sees dashboards and productivity trends for their own reportees only, rather than the full company view an Owner or HR Manager gets — the right level of visibility for day-to-day team management.",
            },
            {
                heading: "Task assignment inside the same view",
                body: "Projects and tasks can be assigned directly from the same dashboard used to track the team's productivity, so managing the work and tracking it happen in one place.",
            },
        ],
        bullets: [
            "Dashboards and productivity trends scoped to their own team only.",
            "Assigns and tracks tasks directly against team members.",
            "Sees idle, late and attendance flags for their own reportees in real time.",
            "No access to company-wide billing, integrations or other teams' data.",
        ],
        mockup: "dashboard",
        faqs: [
            { q: "Can a Team Lead see other teams' data?", a: "No, visibility is scoped strictly to their own team — not the wider company." },
            { q: "Can a Team Lead assign tasks directly from the dashboard?", a: "Yes, task assignment happens from the same view used to track team productivity." },
            { q: "Does a Team Lead see late or idle alerts for their team?", a: "Yes, those alerts appear in real time, scoped to their own reportees." },
        ],
    },
    {
        slug: "employee",
        category: "Team Role",
        tone: "green",
        icon: <FiUser />,
        title: "Employee",
        seoTitle: "Employee Self-Service — Your Own Timer, Timesheets & Leave",
        metaTitle: "Employee Self-Service Software | PrepDesk",
        metaDescription: "Their own timer, timesheets, screenshots and leave — full transparency into their own data, no black box.",
        keywords: "employee self service time tracking, employee transparency monitoring software, employee leave request app",
        lead: "Their own timer, timesheets, screenshots and leave — full transparency into their own data. An employee's view of PrepDesk is entirely their own.",
        sections: [
            {
                heading: "Full visibility into their own record",
                body: "An employee can see exactly what's tracked about their own day — time, apps, screenshots — the same transparency principle that runs through the whole platform, applied at the individual level.",
            },
            {
                heading: "Self-service, not a request to HR",
                body: "Leave requests, timesheets and balances are all accessible directly, without needing to email HR or wait for a manager to pull a report on their behalf.",
            },
        ],
        bullets: [
            "Full visibility into their own tracked time, apps and screenshots — no black box.",
            "Applies for leave and checks balances directly, without an email thread.",
            "Can pause tracking for personal breaks — nothing is captured while paused.",
            "No access to other employees' data — scoped entirely to their own record.",
        ],
        mockup: null,
        faqs: [
            { q: "Can an employee see everything that was tracked about them?", a: "Yes, full transparency into their own time, apps and screenshots is a default part of the employee view." },
            { q: "Can an employee apply for leave without emailing HR?", a: "Yes, leave requests and balance checks are self-service, directly inside PrepDesk." },
            { q: "Can an employee see other team members' data?", a: "No, an employee's access is scoped entirely to their own record." },
        ],
    },
];

export const detailsBySlug = details.reduce((acc, d) => {
    acc[d.slug] = d;
    return acc;
}, {});

export default details;
