const ProductsData = [
    {
        slug: "real-estate-crm",
        name: "PrepRealEstate CRM",
        tagline: "Sales CRM for developers & brokerages",
        category: "Real Estate",
        description: "A sales CRM built for developers & brokerages — lead capture, site-visit tracking, inventory and booking management on one platform.",
        status: "ready",
        link: "/products/real-estate-crm",
    },
    {
        slug: "prepdesk",
        name: "PrepDesk",
        tagline: "Workforce time tracking, attendance & HRMS",
        category: "Workforce & HR",
        description: "Workforce time tracking, attendance, shift rosters and payroll-ready reports for teams working across multiple sites.",
        status: "ready",
        link: "/products/prepdesk",
    },
    {
        slug: "prepcam",
        name: "PrepCam",
        tagline: "AI video intelligence for physical operations",
        category: "AI Video Intelligence",
        description: "Turns the RTSP/CCTV cameras you already have into SOP compliance checks, mobile-phone detection, touchless attendance and zone analytics.",
        status: "ready",
        link: "/products/prepcam",
    },
    {
        slug: "prepwhatsbot",
        name: "PrepWhatBot",
        tagline: "AI WhatsApp automation & bulk campaigns",
        category: "AI Marketing Automation",
        description: "Turns your WhatsApp number into an AI-trained rep — auto-replies, a no-code flow builder, compliant bulk campaigns and a shared inbox.",
        status: "ready",
        link: "/products/prepwhatsbot",
    },
    {
        slug: "prepcommerce",
        name: "PrepCommerce",
        tagline: "AI-native commerce OS for every channel",
        category: "Commerce OS",
        description: "Unifies your storefront, inventory and orders across website, marketplaces, Instagram and WhatsApp — with payments, shipping and AI insights built in.",
        status: "ready",
        link: "/products/prepcommerce",
    },
    {
        slug: "prepjewellery",
        name: "PrepJewellery ERP",
        tagline: "Automation-first ERP for jewellery retail",
        category: "Jewellery ERP",
        description: "Runs sales, purchase, karigar, manufacturing, repairs and gold exchange on one engine — with direct gold-testing hardware integration and GST billing.",
        status: "ready",
        link: "/products/prepjewellery",
    },
    {
        slug: "prepschool",
        name: "PrepSchool",
        tagline: "Preschool & daycare management platform",
        category: "Education",
        description: "A preschool & daycare ERP — admissions, attendance, fees, the digital diary, parent communication and transport tracking on one platform.",
        status: "ready",
        link: "/products/prepschool",
    },
    {
        slug: "prepprint",
        name: "PrepPrint",
        tagline: "Print shop & press management ERP",
        category: "Print & Press ERP",
        description: "Quotations, job tracking, design files, GST billing, stock and machine scheduling for print shops and press operations, on one platform.",
        status: "ready",
        link: "/products/prepprint",
    },
];

export default ProductsData;
